### ISSUE TITLE
README edit: Add customization info for icons and adding more icons

### ISSUE THREAD

**Issue by kaustubhhiware** [athityakumar/colorls#1]
As discussed in DM, new icons can be added for undetected file systems/extensions by editing `formats.yaml` and using the [nerd-fonts README](https://github.com/ryanoasis/nerd-fonts#seti-ui--custom) for reference.

Apart from that, if someone wishes to add more files, refer to the above README link. There is a file extension for each provided icon.

**Comment by kaustubhhiware** [comment]
I'm adding a list of file types for which icons are to be added. Feel free to tick off the ones that are covered:
- [ ] .npm and the likes
- [ ] .aux, .out, .tex
- [ ] ppt, pptx
- [ ] .pdf
- [ ] images (the icon for this specific one is not rendering I think)

**Comment by athityakumar** [comment]
I think that the last 3 ones are added already. But npm, out, tex and related ones are pending.

**Comment by kaustubhhiware** [comment]
I think there's some trouble rendering those particular 3 extensions. Perhaps, some more commonly icons could be used ?

**Comment by athityakumar** [comment]
Sure. but it renders just fine for me, screenshots would probably help.

**Comment by kaustubhhiware** [comment]
Edited comment

**Comment by kaustubhhiware** [comment]
Ping @athityakumar .
Updates with screenshots

**Comment by athityakumar** [comment]
@kaustubhhiware - I see. `nerdfont` or `awesome` font? I'm using `awesome-config` from oh-my-zsh, and it renders like this - 

![image](https://user-images.githubusercontent.com/17109060/27761885-ceda3d58-5e83-11e7-9312-9fcfadbfa87a.png)

**Comment by kaustubhhiware** [comment]
I have `nerdfont` and `powerline-font` installed in my system. I can get back to you after installing `awesome` font as well.

**Comment by kaustubhhiware** [comment]
As discussed, only nerd fonts is being used, the rendering problem is concerned with my system.

**Comment by athityakumar** [comment]
Hmm, weird. Did you do a full install of nerd-font, @kaustubhhiware?
