### ISSUE TITLE
'\uF481' is for links but has been assigned to YAML

### ISSUE THREAD

**Issue by KSXGitHub** [athityakumar/colorls#106]
This is '\uF481':
![image](https://user-images.githubusercontent.com/11488886/29672847-97d9d71e-8917-11e7-9248-ce42d17b7fbc.png)

This [line](https://github.com/athityakumar/colorls/blob/fb40c72b1542084433088eb9020198f337a8874f/lib/yaml/files.yaml#L66)

**Comment by athityakumar** [comment]
Hmm, and any icon you'd like to suggest for yaml?

**Comment by KSXGitHub** [comment]
How about this?
![image](https://user-images.githubusercontent.com/11488886/29675253-db7ab91e-891e-11e7-8d59-d1d880202ecd.png)

I got this idea from file-icons ([atom](https://atom.io/packages/file-icons)/[vscode](https://github.com/vscode-icons/vscode-iconshttps://marketplace.visualstudio.com/items?itemName=file-icons.file-icons) plugin that provides file icons). They also use the icons above for `json`, `cson` and other data serialization formats.

**Comment by athityakumar** [comment]
All the 3 icons resemble redis and similar db related stuff, as the names say. How about aliasing yaml icon to json?

**Comment by KSXGitHub** [comment]
Technically, YAML is a superset of JSON. The thing is, file-icons font has way more icon than Nerd Font, but it uses database icon for json, cson, yaml, etc.

**Comment by athityakumar** [comment]
Hmm. But I just felt the existing json icon (`{}`) to be intuitive as json files do often contain nested hash (`{}` in ruby) data. Similar background story to current yaml icon. But these 3 definitely feel like redis / db-related to me. Or maybe we could have a look at some other icons.

**Comment by KSXGitHub** [comment]
Some other languages such as JavaScript and Python use `{}` to embed json object too, but they're also use `[]` to embed json array, not to mention that most languages don't embed json code. ITOH, json, cson, yaml are always data
