### ISSUE TITLE
Better icon for git

### ISSUE THREAD

**Issue by KSXGitHub** [athityakumar/colorls#107]
Currently, git icon is 3 letters "git" which isn't an icon. I think this is better

![image](https://user-images.githubusercontent.com/11488886/29678029-4a13dbf0-8927-11e7-95ac-bec518e39b26.png)

**Comment by athityakumar** [comment]
Tried this out, but it's too small to be visible. You may also want to have a look at #33 discussion.

**Comment by KSXGitHub** [comment]
I see, it cannot be fixed unless Nerd Font fixes the icon
