### ISSUE TITLE
You may want to merge these branches

### ISSUE THREAD

**Issue by KSXGitHub** [athityakumar/colorls#108]
I wanted to open a pull request but [this guide](https://github.com/athityakumar/colorls/blob/master/CONTRIBUTING.md) tells me not to.

I added some folder icons for `.atom`, `.vscode`, and `.github`: https://github.com/KSXGitHub/colorls/tree/new-folder-icons

I also added some file icons and fix things that don't make sense: https://github.com/KSXGitHub/colorls/tree/new-file-icons

![Screenshot](https://user-images.githubusercontent.com/11488886/29683843-031bca7e-893a-11e7-936e-f7aaf36738b2.png)

**Comment by athityakumar** [comment]
New folder icons look good. I commented 1 minor change in the new files commit. But sure, open PRs for both (or even a single PR combining both would do) 😄

**Comment by athityakumar** [comment]
And thanks for following the CONTRIBUTION GUIDELINES 👍
