### ISSUE TITLE
Add an equivalent Python3 script

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/colorls#11]
Suggested by @janga1997 - Rather than having colorls depend on Ruby, a Python script called colorls.py could be made from colorls.rb for making it easier for Pythonists.

My note - Creating a Python script should be easy. Requirements are on 3 libraries - one for colorizing string, one for reading from yaml files, and one for finding the width of current terminal screen. Once this is investigated, translation of colorls.rb to colorls.py line by line should be easy. 🎉 

Ping @kaustubhhiware @americast

**Comment by kaustubhhiware** [comment]
* Why? Is it really needed?
This is coming from a person who has never used ruby, and has been using python heavily for the last year.
* Are there any advantages of using python for `colorls`?
 The current **max** time taken in my root directory is 226ms as per commit `405b3f`, no one would complain for a better speed at this point of time.

Here is my brutally honest opinion: Anyone who thinks `colorls` is worth cloning and trying out shouldn't have a problem with installing ruby. Ruby is not the only dependency for this project, you'd have to install the fonts anyway.
If switching/porting the project to python has any tangible improvements/benefits, you could start working on it right away.

**Comment by americast** [comment]
@kaustubhhiware Agreed to most of the points except that
> no one would complain for a better speed at this point of time.

Well, as per the latest commit `bbf78a`, it took ~5 secs for `colorls` to load for the first time.

**Comment by janga1997** [comment]
@kaustubhhiware I was the one who suggested this, and although installing ruby isn't a major hassle, I would prefer something that works directly in Python. It isn't really a very long ruby script, so it shouldn't take much time.

**Comment by kaustubhhiware** [comment]
Hi @janga1997 !
As Athitya has mentioned above, I know you've suggested this. But are there any advantages of porting it to python? Is convenience the only benefit from this? 
If the cause of concern is only convenience, the project can be ported to shell. Since no GUI is involved, [shell would be way faster than python](https://stackoverflow.com/a/14476979).

**Comment by kaustubhhiware** [comment]
@americast Can you temporarily use a theme in a shell emulator like zsh / fish which displays the exact running time of a process, and time both: lc, and ls. It could possibly be an issue with your system, though I'm not entirely sure about that.

**Comment by athityakumar** [comment]
@americast - Does this take 5 seconds when you're having a lot of multitasking (lot of Firefox tabs) or something like that? Or does it normally take 5 seconds? As @kaustubhhiware said, it takes barely 0.3s at max for me too.

@kaustubhhiware - Maybe it's​ worth noting that @americast's system has 2GB RAM?

**Comment by americast** [comment]
@athityakumar @kaustubhhiware I did a tic-toc in bash by issuing `time lc`. (This does not work in zsh, I don't know why!)

2.834s when firefox is open with a lot of tabs (10)
2.385s when firefox is open with less number of tabs (3) and
0.417s when firefox is not open.

Also, if I issue `lc` for the second time, (in all the states), it takes just 0.395s.

**Comment by athityakumar** [comment]
`colorls` is now a gem. I don't think it'd get easier to install than `gem install colorls` 😅

Closing this issue for now, but feel free to reopen it. 😄
