### ISSUE TITLE
WARNING:  You don't have /home/shadow/.gem/ruby/2.4.0/bin in your PATH,

### ISSUE THREAD

**Issue by shadow-cpp** [athityakumar/colorls#111]
WARNING:  You don't have /home/shadow/.gem/ruby/2.4.0/bin in your PATH,
	  gem executables will not run.
Successfully installed colorls-0.1.7
Parsing documentation for colorls-0.1.7

**Comment by athityakumar** [comment]
@shadow-cpp : Try adding `export PATH=$PATH:/home/shadow/.gem/ruby/2.4.0/bin` , and re-install colorls gem.

**Comment by shadow-cpp** [comment]
Solution thanks
