### ISSUE TITLE
Release to package managers (like Homebrew)

### ISSUE THREAD

**Issue by EricSoldierer** [athityakumar/colorls#12]
Can this be turned into a Oh My Zsh plugin ?

**Comment by athityakumar** [comment]
Thanks for opening this issue, @EricSoldierer. I had contemplated this before writing this in Ruby. Now, the thing with making this as a oh-my-zsh plugin is,

- It is a Ruby script (`colorls.rb`), which would need to be translated to a shell script. This could be unnecessarily difficult, but could be done if it gets some help from the community. 😄 
- It restricts the usage of colorls in just bash / fish shells. Rather, in it's current state, it can be used in any shell as long as dependencies (Ruby and fonts) are installed.

**Comment by EricSoldierer** [comment]
I see the ruby and font dependency stuff not working out properly via a plugin...
However step 6 could be made optional via a zsh plugin to keep the .zshrc cleaner. This would require install location to be unified.
I installed it to `~/bin` because i don't want a system wide installation. Otherwise `/usr/local/bin` would be a good place.
Maybe add the recommended install locations to the manual ?
Is it an option to add this to homebrew and similar package managers for linux ?

**Comment by athityakumar** [comment]
> Is it an option to add this to homebrew and similar package managers for linux ?

Sure. This project has just begun, and adding this to package managers would make installation easier. 👍

**Comment by athityakumar** [comment]
@EricSoldierer - This project has become a gem now. `gem install colorls` should add the `lc` command automatically. Do you think this suffices? (Even Homebrew requires Ruby. So, why make it home brew dependent rather than making it a gem?) 😄

**Comment by EricSoldierer** [comment]
Nice, yeah a gem is completely fine :)
It does add the `colorls` command. Intentional to not add the `lc` ?

**Comment by athityakumar** [comment]
@EricSoldierer - Yes, `lc` overlaps with [Mono executable](http://manpages.ubuntu.com/manpages/trusty/man1/lc.1.html).

**Comment by EricSoldierer** [comment]
Ok then i guess a local alias is the way to go. Thanks for this tool :)
