### ISSUE TITLE
MacOS Terminal : Use without Knack Regular Nerd Font Complete as default?

### ISSUE THREAD

**Issue by ylluminate** [athityakumar/colorls#127]
Is there any way to make this work with Terminal.app on macOS without having to set the default font to `Knack Regular Nerd Font Complete`?

**Comment by athityakumar** [comment]
I'm not sure if a workaround is possible, but setting the default font to `Knack Regular Nerd Font Complete` definitely works.

**Comment by athityakumar** [comment]
@ylluminate - I think that this font is a **MUST** for the icons to work. Sorry, but I'm afraid you would have to set it as the default / non-unicode font.
