### ISSUE TITLE
Add tests for output of each flag usage and combination

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/colorls#132]
This would probably be the MOST foolproof way of ensuring that everything is working as expected. Earlier, reviewing PRs used to be easier by looking at the Travis CI build logs. However, with increasing number of flag options, it becomes tougher and tougher to manually keep checking the changes. Hence, the need for **ACTUAL** tests (rspec) arises.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [x] Developer mode : Code quality / Tests / Documentation

**Comment by henrebotha** [comment]
@athityakumar I'd like to do some work on this. I can't promise the full extent of every possible flag combination, but I can at least get us started with some basics.

**Comment by athityakumar** [comment]
@henrebotha - Sure, feel free to get started. Thanks for working on this. 😄
