### ISSUE TITLE
Add support for rubocop-rspec

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/colorls#134]
### Description

Rubocop-rspec introduces lot more Rubocop rules to the specs, so that the tests are all sane, DRY and readable.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [x] Developer mode : Code quality / Tests / Documentation

**Comment by athityakumar** [comment]
@henrebotha - In case you'd like to contribute more, I'd recommend this issue next as it's pretty relevant to the tests you added in PR #133. 😄

**Comment by lucienemlf** [comment]
I would like to work on this

**Comment by athityakumar** [comment]
@henrebotha - Let us know if you've already started working on this. Else, I can assign this issue to @lucienemlf.

**Comment by henrebotha** [comment]
You can assign it, I've done enough damage. :P

**Comment by athityakumar** [comment]
@henrebotha - Alright then. No issues. 😄 
@lucienemlf - Feel free to work on this issue. I assign this to you.

**Comment by athityakumar** [comment]
Any updates, @lucienemlf?
