### ISSUE TITLE
Better tab completion

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/colorls#136]
### Description

The current tab completion does work for flags. But it'd be better to have functionality of completing to flags when a match is found, and works with normal directory tab complete when no match is found.

For example, `colorls ../<TAB>` doesn't complete the directories.

- Relevant Issues : #99 
- Relevant PRs : #135 
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

Ping @rohitner - Do you think this could be made better?

**Comment by rohitner** [comment]
@athityakumar replacing 
`complete -W "${_colorls_options}" 'colorls'` with 
`complete -f -W "${_colorls_options}" 'colorls'`

**Comment by athityakumar** [comment]
Oh, that's a better way. But could the flag options come in only when the completing ARG isn't empty? Like,

`colorls <TAB>` - All Files and directories
`colorls ../<TAB>`- Matching Files and directories
`colorls -<TAB>` - Matching Flags

**Comment by rohitner** [comment]
`colorls -<TAB>` does show matching flags only and not the directories.

**Comment by athityakumar** [comment]
I checked that, but consider scenario 1 (`colorls <TAB>`) : wouldn't it better to atleast group the flags and files separately? Give this a try.

**Comment by GeneralD** [comment]
btw, [zsh-completion-generator](https://github.com/RobSis/zsh-completion-generator) makes completion perfectly.
colorls -\<TAB\> shows

```
--all                      -a                 -- do not ignore entries starting with .
--almost-all               -A                 -- do not list . and ..
--dark                                        -- use dark color scheme
--dirs                     -d                 -- show only directories
--files                    -f                 -- show only files
--git-status               --gs               -- show git status for each file
--group-directories-first  --sort-dirs  --sd  -- sort directories first
--help                     -h                 -- prints this help
--light                                       -- use light color scheme
--long                     -l                 -- use a long listing format
--report                   -r                 -- show brief report
--sort-files               --sf               -- sort files first
--tree                     -t                 -- shows tree view of the directory
--version                                     -- show version
-1                                            -- list one file per line
```
