### ISSUE TITLE
Ruby-Terminfo : failed to build gem native extensions

### ISSUE THREAD

**Issue by Ridonk** [athityakumar/colorls#137]
### Description

Attempting to install colorls and encountering some errors. 

Initial error log:

```
sudo gem install colorls            
Building native extensions.  This could take a while...
ERROR:  Error installing colorls:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ruby-terminfo-0.1.1
/usr/bin/ruby2.3 -r ./siteconf20171026-12815-zqe9t0.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ruby-terminfo-0.1.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ruby-terminfo-0.1.1/gem_make.out
```
Attempted `sudo apt-get install libncurses5-dev`

No change.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [x] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by athityakumar** [comment]
@Ridonk - Hey, thanks for opening this issue. Try `gem install ncurses-ruby`

**Comment by Ridonk** [comment]
Hey, just tried it. Got a similar error, seen below:
https://pastebin.com/tUiHRRdv
Maybe a dependency issue from ncurses?

**Comment by athityakumar** [comment]
@Ridonk - The terminfo dependency has been removed, and replaced in v1.0.6. Please try `gem install colorls` again. 😄

**Comment by Ridonk** [comment]
Tried again, error pasted below:

`sudo gem install colorls          
[sudo] password for georgeddunbar: 
Fetching: rainbow-2.2.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing colorls:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.2/ext
/usr/bin/ruby2.3 mkrf_conf.rb

current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.2/ext
/usr/bin/ruby2.3 -rubygems /usr/share/rubygems-integration/all/gems/rake-12.0.0/exe/rake RUBYARCHDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2 RUBYLIBDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2
/usr/bin/ruby2.3: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-12.0.0/exe/rake (LoadError)

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/rainbow-2.2.2 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.2/gem_make.out`

Since it said rake failed, I did sudo gem install rake, a voila! All good now. Thanks!

**Comment by valmormn** [comment]
I get this error after: `sudo gem install colorls`

```Building native extensions. This could take a while...
ERROR:  Error installing colorls:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/clocale-0.0.4/ext/clocale
/usr/bin/ruby2.5 -r ./siteconf20190528-6106-mcuh3s.rb extconf.rb
checking for locale.h... yes
checking for setlocale()... yes
checking for strcoll()... yes
checking for strxfrm()... yes
creating Makefile

current directory: /var/lib/gems/2.5.0/gems/clocale-0.0.4/ext/clocale
make "DESTDIR=" clean
sh: 1: make: not found

current directory: /var/lib/gems/2.5.0/gems/clocale-0.0.4/ext/clocale
make "DESTDIR="
sh: 1: make: not found

make failed, exit code 127

Gem files will remain installed in /var/lib/gems/2.5.0/gems/clocale-0.0.4 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/clocale-0.0.4/gem_make.out
```

**Comment by angelod1as** [comment]
Was this solved? I'm having the same issue.

**Comment by avdv** [comment]
@angelod1as this issue is over 3 years old and was probably about a different problem. Just create a new issue and post the error message, the log file and your system info.
