### ISSUE TITLE
Support for more colors

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/colorls#140]
### Description

Currently, `colorize` gem is doing a good job of colorizing strings. However, not many colors are supported. Whereas, on the other hand, the Rainbow gem provides more eye-candies.

![image](https://user-images.githubusercontent.com/17109060/32134738-2cef4182-bc11-11e7-89d7-5088aca531b5.png)
![image](https://user-images.githubusercontent.com/17109060/32134741-410b3ca2-bc11-11e7-8916-7509ad144d0d.png)
![image](https://user-images.githubusercontent.com/17109060/32134742-4b1183f0-bc11-11e7-9acd-fa0550013a96.png)
![image](https://user-images.githubusercontent.com/17109060/32134744-56293a12-bc11-11e7-8c54-2f016287c532.png)
![image](https://user-images.githubusercontent.com/17109060/32134746-68abe84c-bc11-11e7-9926-1324be9dead3.png)

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by athityakumar** [comment]
Added with #142

**Comment by harmnot** [comment]
is there any configuration to make different colours for each type files, EX: .js, .css, .html, and else?
