### ISSUE TITLE
Sort contents by size

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/colorls#152]
### Description

Like sorting by files / dirs, sorting by modification time (`--ss` or `--sort-size`) would be a useful flag.

- Relevant Issues : (none)
- Relevant PRs : #155 
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by neshmi** [comment]
I'll jump on this! :)

**Comment by athityakumar** [comment]
@neshmi - A similar thing (sort by time) is being dealt with, in PR #139. Have a look at it too, before proceeding. I'm assigning this to you. 😄

**Comment by neshmi** [comment]
Thanks, happy to take on both.
