### ISSUE TITLE
Add support for gitignore-d files and dirs

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/colorls#156]
### Description

Currently, all files and dirs that don't appear in the `git status --short` list is assumed to be tracked by git. Rather, ignored files and dirs should be handled as a separate case by parsing `git ls-files --others -i --exclude-standard`.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by rohitner** [comment]
So an 'I' instead of a tickmark when we hit `colorls --gs`. Is this what you mean?

**Comment by athityakumar** [comment]
@rohitner - Just an empty space for the ignored files or directory (with all files ignored) will do the job too.
