### ISSUE TITLE
can't use lc

### ISSUE THREAD

**Issue by huangda2100** [athityakumar/colorls#16]
when i use "lc",it appears this /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- colorize (LoadError)
       	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /Users/huangda/colorls/colorls.rb:1:in `<main>'
how to resolve it???

**Comment by athityakumar** [comment]
@huangda2100 - Make sure you have install all required gems with 

```sh
cd /path/to/colorls
gem install bundler
bundle install
```

**Comment by huangda2100** [comment]
@athityakumar thank you and sorry to ask you such weak intelligence question

**Comment by athityakumar** [comment]
@huangda2100 - No issues at all. Let me know if `lc` works with a screenshot - then, this issue can be closed. 😄

**Comment by huangda2100** [comment]
@athityakumar it works with lc but i don't know how to set icons:(

**Comment by athityakumar** [comment]
As described in the installation procedure, please install nerd-font font. Then, icons will appear with `lc`. If you've an iTerm2, take special note of enabling icon font on iTerm2 as described in README.

**Comment by huangda2100** [comment]
@athityakumar thank you very much, i will try

**Comment by huangda2100** [comment]
@athityakumar everything is okay now. I really want this can be used in every command, goahead!

**Comment by athityakumar** [comment]
> everything is okay now.

I'm glad I was able to help. 😄 

> I really want this can be used in every command, goahead!

Can you explain what all you'd like `lc` to be able to do?

BTW, feel free to close this issue after this discussion. 😄

**Comment by athityakumar** [comment]
Ping @huangda2100
