### ISSUE TITLE
tree depth

### ISSUE THREAD

**Issue by luisdavim** [athityakumar/colorls#168]
### Description

Add an option to specify a depth for the tree (`-t`) option, like the `-L` option in the tree command.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by athityakumar** [comment]
Sounds good. Thanks for opening this issue, @luisdavim. In case anyone is interested to work on this issue, the current tree method works by recursion and a tree_depth argument has to be added to terminate from within the recursion.

**Comment by mkjmdski** [comment]
What is the current progress on this feature request?

**Comment by avdv** [comment]
Fixed by #253
