### ISSUE TITLE
colorls 'name that contains spaces'

### ISSUE THREAD

**Issue by KSXGitHub** [athityakumar/colorls#172]
### Description

Pass an argument that contains spaces to colorls.

```sh
colorls 'name that  contains   spaces'
colorls name\ that\ \ contains\ \ \ spaces
```

#### Expected

colorls treats the provided argument as a single entity.

#### Received

colorls treats each word in the argument as an entity, resulting in reading multiple invalid entities.

![image](https://user-images.githubusercontent.com/11488886/34479048-ff9972b2-efd6-11e7-87c5-4e5f65a83b5b.png)

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Which version are you using? I cannot reproduce this, neither with version 1.0.9 nor the latest revision of the master branch...

**Comment by KSXGitHub** [comment]
Oops! It was because of my alias (`ls`), no problem in `colorls`, I'm sorry!
