### ISSUE TITLE
Option to choose columns with -l flag

### ISSUE THREAD

**Issue by schovi** [athityakumar/colorls#174]
### Description

Would be awesome to be able to select which columns I want to see with `-l` flag. Many terminal tutorials and configs come with command `ll` which is alias for `ls -la`. I use it exclusively whole day and 99% of cases I only want size and name of file itself (in this case icon and gitstatus too).
With classic `ls` it can be done with `| awk '{print $....}'`, but it does not work with `colorls`.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by sbibauw** [comment]
A partial solution would be to reproduce `-g` (= no owner column) and `-o` (= no group information column) options from `ls`.

**Comment by t-mangoe** [comment]
Regarding this issue, I tried to add `-g` and `-o` options. 
I intend to open a pull request, so please check my code.

**Comment by avdv** [comment]
Support for `-g` and `-o` implemented in #417 (plus support for `-G` / `--no-group`) by @t-mangoe.

If you need anything special you could also use `colorls --color=always -l | awk '{print ...}'`...
