### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by billimek** [athityakumar/colorls#175]
### Description
The current published release is v1.0.1 and there have been 93 commits to master since this release.

Is it possible to get a new release of colorls cut, so we can benefit from these changes and features with a simple `gem install colorls` ?

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [X] Installation
  - [ ] Font-related
  - [X] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by athityakumar** [comment]
Hey @billimek - thanks for reminding about the new release. The newest version v1.1.0 has been released. 😄
