### ISSUE TITLE
Recognize Jupyter's `.ipynb` files

### ISSUE THREAD

**Issue by acarl005** [athityakumar/colorls#177]
### Description

Thanks for opening this issue. Add a brief description of what this issue is, and how to recreate it. Do tag the relevant issue(s) and PR(s) below. If required, add some screenshot(s) to showcase the issue.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

I propose adding the following to the `file_aliases.yaml`:
```yaml
ipynb:    py
```

Jupyter iPython notebooks are widely popular in data science and research and I think that merits recognition with a python icon.

**Comment by athityakumar** [comment]
Sure. Feel free to send in a PR. 😄

**Comment by acarl005** [comment]
done! #181
