### ISSUE TITLE
Error installing colorls

### ISSUE THREAD

**Issue by blackjezreel** [athityakumar/colorls#184]
im using linux mint 18.3
i got this error when i run `sudo gem install colorls`

> Building native extensions. This could take a while...
ERROR:  Error installing colorls:
ERROR: Failed to build gem native extension.
current directory: /var/lib/gems/2.3.0/gems/clocale-0.0.3/ext/clocale
/usr/bin/ruby2.3 -r ./siteconf20180207-8536-v1bj38.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
extconf failed, exit code 1
Gem files will remain installed in /var/lib/gems/2.3.0/gems/clocale-0.0.3 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/clocale-0.0.3/gem_make.out

here is my `gem list` : 

> bigdecimal (default: 1.2.8)
bundler (default: 1.16.1)
colorize (0.8.1)
did_you_mean (1.0.0)
diffy (3.2.0)
facets (3.1.0)
filesize (0.1.1)
gist (4.6.2, 4.5.0)
io-console (default: 0.4.5)
json (default: 1.8.3)
make (0.3.1)
minitest (5.8.4)
net-telnet (0.1.1)
power_assert (0.2.7)
psych (default: 2.0.17)
rainbow (3.0.0)
rake (12.3.0, 10.5.0)
rdoc (default: 4.2.1)
rubygems-update (2.7.5)
test-unit (3.1.7)

i also have installed `libncursesw5-dev` and `libncurses5-dev`

Thanks for helping :D

**Comment by avdv** [comment]
You need to install make, Ruby headers (ruby-dev) and a C compiler (ie. gcc) in order to build native extensions.

**Comment by blackjezreel** [comment]
@avdv thanks for replying
i have installed all of that package but still got the problem

**Comment by blackjezreel** [comment]
[solved] 
I do `sudo apt install --reinstall make` and it fix the problem.

**Comment by insign** [comment]
`sudo apt install ruby-dev gcc make` worked for me.

**Comment by BlackShadow334** [comment]
I am using ubantu terminal in windows 10 . I got same problem.
`sudo apt install --reinstall make`  didn't work for me.
but 
`sudo apt install ruby-dev gcc make` worked.

**Comment by scriptshadow** [comment]
> 
> 
> I am using ubantu terminal in windows 10 . I got same problem. `sudo apt install --reinstall make` didn't work for me. but `sudo apt install ruby-dev gcc make` worked.

Work for me on debian 10 and Ubuntu 20.4
