### ISSUE TITLE
List files sorted by column rather than by row

### ISSUE THREAD

**Issue by ghost** [athityakumar/colorls#189]
### Description

Long lists of files are (IMO) much easier to read if they are sorted by column, i.e.

```
a d
b e
c f
```
rather than
```
a b
c d
e f
```

This is the way output is sorted in ls. If you don't want this to be default behavior, please at least add a flag for it.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by mccarths** [comment]
I'd be happy to take this one on if that's ok?

**Comment by avdv** [comment]
Hi @mccarths, sorry I missed your comment here. Sure, if you want to tackle this, go ahead! :+1:
