### ISSUE TITLE
"colorls -l" -- incorrect alignment when file size < 1KiB

### ISSUE THREAD

**Issue by acavalin** [athityakumar/colorls#190]
### Description

Hello, if a file weights less than 1KiB the columns are not aligned, see example:

```
rwxr-xr-x cloud cloud 4 KiB Fri Apr 6 16:05:58 2018  folder1/
rwxr-xr-x cloud cloud 4 KiB Fri Apr 6 16:02:18 2018  folder2/
rwxr-xr-x cloud cloud 1016 B Wed Jun 29 20:49:22 2016  file.rb
rwxr-xr-x cloud cloud 4 KiB Wed Aug 6 23:06:20 2014  folder3/
rwxr-xr-x cloud cloud 4 KiB Wed Mar 21 11:08:24 2018  folder4/
```

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by jmks** [comment]
I think I found a simple fix.
