### ISSUE TITLE
Icons don't appear in VSCode terminal ?

### ISSUE THREAD

**Issue by ianizaguirre** [athityakumar/colorls#191]
Icons appear normally in my terminal on my dekstop but in my VS Code integrated terminal , the icons appear as empty boxs. Is it not supposed to work in the integrated terminal in VS Code?

**Comment by ianizaguirre** [comment]
Yes, are you having trouble?

**Comment by lyndsey-ferguson** [comment]
I have the empty boxes too. I tried installing the Nerd font, and changing the terminal font setting to use that font. Did you do something else?

**Comment by ianizaguirre** [comment]
Yea, I added this to my VS code settings: 

‘’’

  // ========== Integrated Terminal ==========
  "terminal.integrated.fontSize": 19,
  "terminal.integrated.lineHeight": 1.2,
  "terminal.integrated.fontFamily": "Hack Nerd Font",
  "terminal.integrated.fontWeightBold": "normal",

‘’’

**Comment by lyndsey-ferguson** [comment]
I'll check it out

**Comment by OscarSilvaOfficial** [comment]
It works, thanks!!!

**Comment by kohane27** [comment]
@ianizaguirre thank you so much! Not setting the `terminal.integrated.fontFamily` was the reason that the icons couldn't be displayed.
