### ISSUE TITLE
-X flag to sort alphabetically by entry extension

### ISSUE THREAD

**Issue by wviechtb** [athityakumar/colorls#199]
### Description

I like flag `-X` of `ls` which sorts entries alphabetically by their extension (combined with `--group-directories-first`, but this is already available in `colorls`). Is this something that could be added? Thanks for considering this option.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [X] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by billiams** [comment]
@avdv this feature doesn't seem to be incorporated with the current version of colorls. Did it get removed?

**Comment by avdv** [comment]
@billiams no, there just hasn't been a release for a while...

If you feel (a bit) adventurous you can install a pre-release with `gem install --pre colorls` which has all the latest features.

**Comment by ianizaguirre** [comment]
why doesn't someone push an official next release ?

**Comment by billiams** [comment]
@avdv okay will do, thanks for the response.
