### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/colorls#20]

**Comment by kaustubhhiware** [comment]
@athityakumar This is pretty simple. Just go to Insights> Community . You will see what you want. This was a recent update by Github. Once you read this, I think you can close the issue within an hour, if not less.

**Comment by athityakumar** [comment]
@kaustubhhiware - Thanks, added `CONTRIBUTION.md`.

**Comment by kaustubhhiware** [comment]
@athityakumar , You should mention the contributing guide at the end of the README. Generally, that helps for new contributors, who wouldn't straight away head to `CONTRIBUTING.md`.

Reopen the issue, for a while until this is done.

**Comment by athityakumar** [comment]
Isn't it already linked from the README?

**Comment by kaustubhhiware** [comment]
I personally don't think that will suffice.
 Another header with contributing at the very end would be better in my opinion, what do you think ?

**Comment by athityakumar** [comment]
Peace, willing to send a PR? 😉
