### ISSUE TITLE
[SOLVED] setlocale error on startup

### ISSUE THREAD

**Issue by ghyatzo** [athityakumar/colorls#204]
Hello, every time i try to use colorls it goes:
`Traceback (most recent call last):
        4: from /Users/ghyatzo/.rbenv/versions/2.5.1/bin/colorls:23:in '<main>'
        3: from /Users/ghyatzo/.rbenv/versions/2.5.1/bin/colorls:23:in 'load'
        2: from /Users/ghyatzo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/colorls-1.1.1/exe/colorls:5:in '<top (required)>'
        1: from /Users/ghyatzo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/colorls-1.1.1/lib/colorls/flags.rb:38:in 'process'
/Users/ghyatzo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/colorls-1.1.1/lib/colorls/flags.rb:38:in 'setlocale': error calling setlocale(1, "") (RuntimeError)`

my locale output is 
`LANG="it.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=`

what's the deal? any idea? i got none.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [x] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Seems the same problem as in #203. Do you use the Hyper terminal?

What's the output of `defaults read -g AppleLocale`?

**Comment by ghyatzo** [comment]
yes i do, i wanted to try it out.
the output is simply `it_IT`

**Comment by avdv** [comment]
There is (was) an issue in Hyper: https://github.com/zeit/hyper/issues/607 about this problem. Coincidentally with the same locale you're using...

Seems to be fixed in Hyper 2.1.0-canary, but that seems to cause other issues: 

https://github.com/zeit/hyper/issues/3091
