### ISSUE TITLE
Nicer output when passing invalid options

### ISSUE THREAD

**Issue by ghyatzo** [athityakumar/colorls#205]
Hello,
I know this is of secondary importance but i noticed it and while i'm at it i figured i could point it out:

While using colorls (aliased to just ls) if i pass down an invalid argument like `-2` instead of `-1` the resulting error output is the following:

`Traceback (most recent call last):
        5: from /Users/ghyatzo/.rbenv/versions/2.5.1/bin/colorls:23:in '<main>'
        4: from /Users/ghyatzo/.rbenv/versions/2.5.1/bin/colorls:23:in 'load'
        3: from /Users/ghyatzo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/colorls-1.1.1/exe/colorls:5:in '<top (required)>'
        2: from /Users/ghyatzo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/colorls-1.1.1/exe/colorls:5:in 'new'
        1: from /Users/ghyatzo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/colorls-1.1.1/lib/colorls/flags.rb:24:in 'initialize'
/Users/ghyatzo/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/colorls-1.1.1/lib/colorls/flags.rb:161:in 'parse_options': invalid option: -2 (OptionParser::InvalidOption)`

It would be nice if passing a wrong argument would trigger the help screen, just like the majority of terminal apps.
It's not the end of the world but it would feel surely much more polished and solid.
A sort of "i got you buddy, i'm not crashing down the traceback valley"

cheers

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [X] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Thanks for the report, @ghyatzo. I changed the code accordingly to handle this situation. Only I did not want to throw +100 lines of help text at the user if there's an invalid option, just a simple error message and hint about running `colorls --help` -- similar to what GNU ls does.
