### ISSUE TITLE
I cannot use 'ls' in my terminal when my ruby version is higher than the 2.4.3

### ISSUE THREAD

**Issue by kriscard** [athityakumar/colorls#215]
### Description

Since this morning I cannot use the `ls`feature to check all the available directories and file inside a project. I always receive the error message below:
rbenv: colorls: command not found

The `colorls' command exists in these Ruby versions:
  2.4.3

<img width="453" alt="capture d ecran 2018-09-20 11 04 08" src="https://user-images.githubusercontent.com/3465831/45807963-ee27d580-bcc4-11e8-8daa-1efa4b8dadb3.png">

Before I was able to do that when the rbenv global was on ruby 2.5.0. Now I must go on the 2.4.3 version but the ruby version of my project is on ruby 2.5.0. 
I can still work without the `ls` features but It will be better if I can.

Thanks in advance for your help and I hope it's just a little issue (maybe from my part but I did nothing particularly since yesterday). 

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Hi.

I am no export for rbenv, but there's probably a way to force the Ruby version for a single command, regardless of the setting of the current project.

Try this:
```
alias ls='RBENV_VERSION=2.4.3 colorls'
```

**Comment by avdv** [comment]
@kriscard glad it worked out! :smile: I'm closing the issue...
