### ISSUE TITLE
Fira Code Support?

### ISSUE THREAD

**Issue by rjhilgefort** [athityakumar/colorls#216]
### Description

It doesn't seem that [Fira Code](https://github.com/tonsky/FiraCode) is supported, or I just don't have something set-up correctly. I'm just seeing `?` with a box around it as if ligatures could not be found. Fira seems to be working elsewhere in my terminal. Sorry if I'm just missing something dumb!

![image](https://user-images.githubusercontent.com/2034823/46032240-4fcab400-c0b8-11e8-9958-ec4d2529fcc6.png)

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [x] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
You need to use the patched Fira Font, from the Nerd Fonts collection. The patched font is called "Fura Code Nerd Font".

**Comment by rjhilgefort** [comment]
Ah, thanks! I see that in the README now, sorry for the issue.
