### ISSUE TITLE
Make executables bold

### ISSUE THREAD

**Issue by evert-mouw** [athityakumar/colorls#217]
It would be nice to show executable files (such as scripts) using **boldface**.
The classic `ls` has the `-F` option to add symbols to special files, and also gives special files other colors. Finding (broken) symlinks, device files, and executable files quickly makes life easier ;-)

---

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
@HolyWalley sure, go ahead.

**Comment by SauravPrakash98** [comment]
Can I attempt this?  @athityakumar

**Comment by simonrouse9461** [comment]
Is anyone working on this feature?

**Comment by HolyWalley** [comment]
> Is anyone working on this feature?

I'm not.

**Comment by t-mangoe** [comment]
I tried this issue.
I'm creating pull request, so please review my code.

**Comment by avdv** [comment]
Fixed by #405. The long term plan however, would be to support `LS_COLORS` to make everything configurable and not hard code these things.

**Comment by evert-mouw** [comment]
Thanks guys!
