### ISSUE TITLE
output is interleaved with blank lines when passing multiple file arguments (e.g.: *.txt)

### ISSUE THREAD

**Issue by fferri** [athityakumar/colorls#233]
### Description

When passing multiple file arguments, e.g.:

    colorls a.txt b.txt c.txt

or

    colorls *.txt

the output is interleaved with blank lines:

```
$ colorls *.txt
      a.txt

      b.txt

      c.txt

      d.txt
```

For comparison, this is the normal output:

```
$ colorls
      a.txt       b.txt       c.txt       d.txt
```

and this is the long (`-l`) output:

```
$ colorls -l
  rw-r--r--  me  staff    0 B    Mon Oct 29 17:52:05 2018    a.txt
  rw-r--r--  me  staff    0 B    Mon Oct 29 17:52:05 2018    b.txt
  rw-r--r--  me  staff    0 B    Mon Oct 29 17:52:05 2018    c.txt
  rw-r--r--  me  staff    0 B    Mon Oct 29 17:52:05 2018    d.txt
```

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by t-mangoe** [comment]
I investigated this blank line.
In lib/colorls/flags.rb, the following output statement seems to make blank lines in process method.
`puts '' if i.positive?`
(line number is 46)
