### ISSUE TITLE
Encoding::CompatibilityError

### ISSUE THREAD

**Issue by jhartlep** [athityakumar/colorls#242]
### Description

Thanks for opening this issue. Add a brief description of what this issue is, and how to recreate it. Do tag the relevant issue(s) and PR(s) below. If required, add some screenshot(s) to showcase the issue.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [x] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

Hi,
I have an Encoding issue with colorls.
Each time, I use colorls on folders containing files or folders with umlaute (ä,ü,ö etc.), I get this error in the console:

```
Traceback (most recent call last):
	15: from /home/jhartlep/.gem/ruby/2.5.0/bin/colorls:23:in `<main>'
	14: from /home/jhartlep/.gem/ruby/2.5.0/bin/colorls:23:in `load'
	13: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/exe/colorls:5:in `<top (required)>'
	12: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/flags.rb:41:in `process'
	11: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/flags.rb:41:in `each_with_index'
	10: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/flags.rb:41:in `each'
	 9: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/flags.rb:46:in `block in process'
	 8: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/core.rb:38:in `ls'
	 7: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/core.rb:38:in `each'
	 6: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/core.rb:38:in `block in ls'
	 5: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/core.rb:286:in `ls_line'
	 4: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/core.rb:286:in `each_with_index'
	 3: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/core.rb:286:in `each'
	 2: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/core.rb:289:in `block in ls_line'
	 1: from /home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/core.rb:282:in `fetch_string'
/home/jhartlep/.gem/ruby/2.5.0/gems/colorls-1.1.1/lib/colorls/core.rb:282:in `join': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
```

I am using zsh with Powerlevel9k theme and the settings from [here](https://github.com/da-edra/dotfiles).
Is this a problem with colorls? Or with my configuration?

**Comment by avdv** [comment]
Hi.

I suppose you're not using UTF-8 locale settings. What's the output of `locale`?

**Comment by danielmain** [comment]
Im having this problem and the output of calling locale is:

`LANG="de_DE.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=`

**Comment by avdv** [comment]
Try `export LC_CTYPE=e_DE.UTF-8`.

**Comment by danielmain** [comment]
No changes :(

<img width="1086" alt="screenshot 2019-02-21 at 10 05 02" src="https://user-images.githubusercontent.com/4303099/53156738-522a2f00-35c0-11e9-8150-1cd994301a6e.png">

**Comment by avdv** [comment]
There was a copy'n'paste error. I edited the command above.

**Comment by danielmain** [comment]
@avdv thank you!! 

I was so stupid I could have seen it. Thank you again!

**Comment by avdv** [comment]
@danielmain BTW, if you want sorting to work correctly (for german umlauts) you also want to set and export the `LC_COLLATE` variable.

**Comment by caseyomara** [comment]
Thank you for this workaround!

**Comment by Luxcium** [comment]
I probably should open my own issue but I will drop this here like if living on the edge is no big deal ... 

I am not fluent in ruby I am more in shell script I understand the probleme is probably the «é» character in `/home/luxcium/Téléchargements` 

*output*
```
/home/luxcium/Téléchargements
Traceback (most recent call last):
        12: from /home/luxcium/bin/colorls:23:in `<main>'
        11: from /home/luxcium/bin/colorls:23:in `load'
        10: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/exe/colorls:26:in `<top (required)>'
         9: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/flags.rb:43:in `process'
         8: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/flags.rb:43:in `each_with_index'
         7: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/flags.rb:43:in `each'
         6: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/flags.rb:48:in `block in process'
         5: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/flags.rb:48:in `new'
         4: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/core.rb:29:in `initialize'
         3: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/core.rb:86:in `init_contents'
         2: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/core.rb:86:in `map!'
         1: from /home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/core.rb:86:in `block in init_contents'
/home/luxcium/.gem/ruby/gems/colorls-1.4.1/lib/colorls/core.rb:86:in `join': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
/home/luxcium/Téléchargements
 
```

*My shell function in ZSH:*

```
    function ld() {
        (
            local mypath="${@:-$(pwd)}"
            echo ''
            builtin cd "${mypath}"
            pw
            colorls -lA --sd -d "${mypath}"
            pw
            echo "${mypath}"
        )
    }
```

*my locale:*
```
locale      
LANG=fr_CA.UTF-8
LC_CTYPE="fr_CA.UTF-8"
LC_NUMERIC=fr_CA.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE=fr_CA.UTF-8
LC_MONETARY=fr_CA.UTF-8
LC_MESSAGES="fr_CA.UTF-8"
LC_PAPER="fr_CA.UTF-8"
LC_NAME="fr_CA.UTF-8"
LC_ADDRESS="fr_CA.UTF-8"
LC_TELEPHONE="fr_CA.UTF-8"
LC_MEASUREMENT=fr_CA.UTF-8
LC_IDENTIFICATION="fr_CA.UTF-8"
LC_ALL=
```

**Comment by iNoSec2** [comment]
Why closing the issue @avdv when someone else have the same issue...

Anyway i have the same issue with same directory than @Luxcium and the work around from `export LC_CTYPE` didnt made the tricks

**Comment by avdv** [comment]
> Why closing the issue @avdv when someone else have the same issue...

Basically because this issue and the one from Luxcium are not related. So, I created a new issue from Luxcium's comment... #377 and then I fixed it... #408  If you are still seeing that error could mean there is some other problem.

**Comment by avdv** [comment]
This issue should be already fixed. Please re-open if this still happens for you with the latest version.
