### ISSUE TITLE
Identifying file types without an extension

### ISSUE THREAD

**Issue by kaustubhhiware** [athityakumar/colorls#25]
Some files, like `Procfile` are specific to heroku only, but cannot be identified due to lack of an extension. 

Likewise, in certain cases, where the extension itself has dots, like `.travis.yml` or `webpack.tar.gz`, the behaviour in this is taken as per the last extension, and not as per the complete one. Could this be of any concern later?

Also, some of the folders, have a unique naming style, like `gulpfile.js/`, here it is not possible to detect the kind of folder to be rendered (I think a symbol of gulp should be shown here, but that is perhaps nit-picking) since the name might not be specific.

Among the 3 cases pointed out above, the first case could be worked upon. I just wanted to point out the usecases that could be encountered.

**Comment by athityakumar** [comment]
- For `Procfile`, just add it to `files.yaml`. 🎉 
- For `.travis.yml`and `webpack.tar.gz`, it's just recognized as a `.yml` and `.gz` extensions. But is it required to have special icons for them?
- Isn't `gulpfile.js/` detected by adding `gulpfile.js` to the `folders.yaml`? Folders aren't detected by their extensions, they are detected by their names itself.

**Comment by kaustubhhiware** [comment]
> For Procfile, just add it to files.yaml
I'm just pointing out there are going to be more instances like this.

I am not sure if special icons are needed for `.travis.yml`, and the likes. I want to know what you think about this?

**Comment by athityakumar** [comment]
Icons for special filenames have been added by PR #66 😄

**Comment by kaustubhhiware** [comment]
Hmm, now that the provision has been made to add specific filenames, this issue can be closed.
