### ISSUE TITLE
Does not set an error code ($?)

### ISSUE THREAD

**Issue by AlexeyMavrin** [athityakumar/colorls#259]
### Description

Unlike ls, does not set an error code on error [example]:

➜ colorls lalal && echo This text should not show

   Specified path 'lalal' doesn't exist.
This text should not show

[compared to ls]
➜ /bin/ls lalal && echo This text should not show
ls: lalal: No such file or directory

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ X] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Yes, that's true. Kind of a known bug.

**Comment by avdv** [comment]
Um, why did you close it? @AlexeyMavrin

**Comment by AlexeyMavrin** [comment]
Sorry, re-oppening.

**Comment by t-mangoe** [comment]
I think this issue may be solved by using at_exit method.
I have written code and want to send pull request, but writing test code is too difficult for me.
Would you mind if I send pull request without test code？
(I'm sorry for my poor English)

**Comment by avdv** [comment]
> I think this issue may be solved by using at_exit method.
> I have written code and want to send pull request, but writing test code is too difficult for me.
> Would you mind if I send pull request without test code？

Not at all, just open a new PR and I will have a look at it!

**Comment by avdv** [comment]
This should be fixed (there is a check here: https://github.com/athityakumar/colorls/blob/0b61d733de7c6cac19af095fbafea3e3f5b0ec5e/test/checks#L44

-- meaning the the command is expected to fail with exit code 2), please re-open if it still does no work.
