### ISSUE TITLE
Colorls slow

### ISSUE THREAD

**Issue by adrianmihalko** [athityakumar/colorls#260]
It is normal that `colorls` is much slower than `ls`?

<img width="1079" alt="screenshot 2019-02-24 at 13 10 01" src="https://user-images.githubusercontent.com/733361/53298996-80fd0b00-3835-11e9-8b99-4ba85a4f7ecf.png">

There is a noticable lag compared to `ls` which is in everyday use is pretty frustrating.

**Comment by avdv** [comment]
This is addressed in #237.

**Comment by avdv** [comment]
You might try out the branch https://github.com/avdv/colorls/tree/refactor-rendering  and see whether it makes any difference to you.

BTW, which version of colorls and ruby are you using?

Note, that Ruby will always have a startup overhead. What yields `time ruby -e 'puts "hi"' on your machine?

**Comment by adrianmihalko** [comment]
Hmmm.

```
time ruby -e 'puts "hi"'
hi
ruby -e 'puts "hi"'  0.15s user 0.05s system 49% cpu 0.407 total
```

**Comment by avdv** [comment]
> ```
> time ruby -e 'puts "hi"'
> hi
> ruby -e 'puts "hi"'  0.15s user 0.05s system 49% cpu 0.407 total
> ```

Does this change when you run it multiple times in a row? For me, the total time of this command is around 0.09 s on average.

> ```
> $ ruby --version
> ruby 2
> ```
That's weird version number. What kind of system is this? Could upgrade to Ruby 2.5 or 2.6?

**Comment by kakulukia** [comment]
> time ruby -e 'puts "hi"'

`0,05s user 0,02s system 93% cpu 0,072 total`

> time colorls --sd --gs -l

`0,10s user 0,03s system 95% cpu 0,141 total`

> time ls -l 

`0,00s user 0,00s system 62% cpu 0,004 total`

Updating from the default OSX ruby version 2.3 to 2.6.5 results into 

`colorls --gs --sd -l  0,10s user 0,03s system 95% cpu 0,135 total`

Not that much better than before, but it feels a lil snappier. 
Still there might be room for optimisation?

**Comment by avdv** [comment]
> > time ls -l
> 
> `0,00s user 0,00s system 62% cpu 0,004 total`
> 
> Updating from the default OSX ruby version 2.3 to 2.6.5 results into
> 
> `colorls --gs --sd -l 0,10s user 0,03s system 95% cpu 0,135 total`

Of course, it is a bit unfair to compare using the `--gs` option, as this needs to call out to git which adds to the overall time spend.

> Not that much better than before, but it feels a lil snappier.

> Still there might be room for optimisation?
Probably not. At least not from colorls; you would have to wait for Ruby optimizations in a new release.

Out of this reason, I started my own "color ls" which is already mostly compatible with colorls but faster since it is compiled to native code. I am using it on a daily basis, but it's still a bit rough around the edges.

**Comment by kakulukia** [comment]
Is that already usable by someone else? Can i try it out?

**Comment by avdv** [comment]
> Is that already usable by someone else? Can i try it out?

Have a look here: https://github.com/avdv/scalals

Currently, building it is quite involved since it depends on a patched scala-native lib. I am currently looking into providing a binary automatically, but that still needs some time.

**Comment by kakulukia** [comment]
That is by far the most complicated build process i have ever seen! And i was not able to finish compilation. But while compiling i found exa (https://the.exa.website/) which might make you drop your own version of colorls. :]

**Comment by kakulukia** [comment]
i miss the "mark latest modifications" feature tho

**Comment by avdv** [comment]
> But while compiling i found exa ([the.exa.website](https://the.exa.website/)) which might make you drop your own version of colorls. :]

Hardly so :wink:, since it has no icons. And I want to have a drop-in replacement for ls, so that when I log in to a remote system, I can just use the same options to `ls` I am used to, but don't get the icons / colors.

**Comment by kakulukia** [comment]
It has icons, but i agree, its not a drop in replacement with some weird options.

But its fast! 20ms

![Bildschirmfoto 2019-11-19 um 15 57 21](https://user-images.githubusercontent.com/96352/69157490-4b93fe00-0ae5-11ea-872c-26141a7ca86e.png)

**Comment by kakulukia** [comment]
testing lsd now, thx :D

**Comment by jeongmincha** [comment]
![image](https://user-images.githubusercontent.com/4997737/125032193-90104b00-e0c8-11eb-9f0c-d085aba765cf.png)
I know this issue was written a long time ago, but it's SUPER slower on my Macbook Pro :( 
Can I get some help?

**Comment by avdv** [comment]
@jeongmincha Please provide some more details about your system. Is this an ARM based macbook? Which ruby version are you using? And what is the output of `time ruby -e 'require "colorls"'`?

**Comment by jeongmincha** [comment]
@avdv These are the information about my system.
* MacBook Pro 2019, 16-inch (Not ARM-based) 
* Big Sur 11.4
```
> ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
> time ruby -e 'require "colorls"'
ruby -e 'require "colorls"'  0.19s user 0.13s system 15% cpu 2.008 total
```

**Comment by avdv** [comment]
> > ruby -v
> ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
> > time ruby -e 'require "colorls"'
> ruby -e 'require "colorls"'  0.19s user 0.13s system 15% cpu 2.008 total

Wow, so even just loading the colorls gem takes around 2 seconds on your system? :astonished: 

Are you using some kind of ruby version manager like rvm? Could you try this with a different user?

**Comment by jeongmincha** [comment]
@avdv I was using the default ruby and It does not seem that rvm is installed for now.
(I don't know gem is related, but gem -v says 3.0.3)
Is it better to install ruby myself instead of the default ruby?

**Comment by avdv** [comment]
> Is it better to install ruby myself instead of the default ruby?

@jeongmincha You could try, maybe something is broken inside of your gem folder or you have some kind of gem addon installed which slows this down. Installing ruby with homebrew and use this one instead might fix this.
