### ISSUE TITLE
Error happened with colorls -r -sd

### ISSUE THREAD

**Issue by iceman201** [athityakumar/colorls#272]
### Description

![image](https://user-images.githubusercontent.com/5027957/54818059-433cb680-4cfd-11e9-8d9c-a65eb3b8f1a8.png)

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Please look at `colorls --help` which options are available.

There is a difference between long and short options; short options begin with a single dash, long options with double dashes. Short options can be combined together, `colorls -l -r` is the same as `colorls -lr`.

One may shorten options when the prefix used is unambiguous, e.g. `--he` is equivalent to `--help`.

Your option is indeed ambiguous, use `--sd` instead.
