### ISSUE TITLE
script icons don't show

### ISSUE THREAD

**Issue by hhlp** [athityakumar/colorls#278]
### Description

For some strange case I can't see some Icons, it happen only with scripts icon :

1. bash config
2. zsh config
3. script files

- Type of issue :
  - [x] Installation
  - [x] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

I follow all step, I'm in fedora 30 and my shell is ZSH and using oh-my-zsh too, I remember I didn't have this problem in fedora 29.

![Captura de pantalla de 2019-04-12 09-55-14](https://user-images.githubusercontent.com/2659606/56021485-d4ee8100-5d09-11e9-8d71-18cae8048ca2.png)

Regards.,

**Comment by avdv** [comment]
Which terminal are you using? Have you installed and configured one of the need fonts for the terminal?

**Comment by hhlp** [comment]
ahh I make I mistake I change other (DOCUMENT) not the correct one (MONOSPACE)
