### ISSUE TITLE
Support setuid, setgid and sticky bit

### ISSUE THREAD

**Issue by Yamp** [athityakumar/colorls#279]
### Description

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

```
colorls -la /usr/local/Cellar/findutils/4.6.0/bin/gupdatedb
rwxr-xr-x    wheel   96 B    Mon Mar 18 11:59:24 2019  gupdatedb
```
```
ls -la /usr/local/Cellar/findutils/4.6.0/bin/gupdatedb
-rwsr-xr-x  1 root  wheel  96 Mar 18 11:59 /usr/local/Cellar/findutils/4.6.0/bin/gupdatedb
```

There are no `s` file permission flag is colorls output, for example.

**Comment by avdv** [comment]
Duplicate of #197
