### ISSUE TITLE
No patched fonts of powerline nerd-font and/or font-awesome

### ISSUE THREAD

**Issue by gamaralf** [athityakumar/colorls#288]
### Description

On the "Instalation" section of the README, it is written:
Install the patched fonts of powerline nerd-font and/or font-awesome. Have a look at the Nerd Font README for more installation instructions.

I have checked the linked page (https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md) but found no downloads for "patched fonts of powerline nerd-font and/or font-awesome". Do they go by another name?

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [X] Installation
  - [X] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by DannyBen** [comment]
Yes, I also want to add that this section of the README should probably be more specific and provide direct links as to what font needs to be installed **exactly**. The link to the nerd font README is confusing, as there are dozens of fonts and sets and installation instructions there.

**Comment by avdv** [comment]
Simply install the one you like. Then, configure it for your terminal and you're set.


On May 24, 2019 9:30:33 AM GMT+02:00, Danny Ben Shitrit <notifications@github.com> wrote:
>Yes, I also want to add that this section of the README should probably
>be more specific and provide direct links as to what font needs to be
>installed **exactly**. The link to the nerd font README is confusing,
>as there are dozens of fonts and sets and installation instructions
>there.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/athityakumar/colorls/issues/288#issuecomment-495504070

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by avdv** [comment]
> Yes, I also want to add that this section of the README should probably be more specific and provide direct links as to what font needs to be installed **exactly**.

That's impossible. The instructions in the nerd font README are complex due to the fact that there are diverse operating systems and thus installation methods. There is not **the one** font you need to install, it depends on your OS / application / visual preference. Of course, the safest bet would be to install *all* of them, but that would be overkill.

I am willing to improve the README, but I do not see how.

**Comment by ryanoasis** [comment]
my 2 cents: you could link to https://www.nerdfonts.com/font-downloads or even https://github.com/ryanoasis/nerd-fonts/releases/latest

**Comment by avdv** [comment]
Thanks @ryanoasis ! I just updated the README to make it clear that users should simply download a Nerd Font. That does not really solve the installation / configuration part but it reduces the confusion because of the wording.
