### ISSUE TITLE
current implementation does not show number of links

### ISSUE THREAD

**Issue by alejandrogarciasalas** [athityakumar/colorls#293]
### Description
I am doing some fiddling with hard links and it seems like colorls is not displaying the number of links on the 2nd row after the file's permissions

**BSD ls (ls --version =1.1.1)**
![Screen Shot 2019-06-04 at 1 36 37 PM](https://user-images.githubusercontent.com/4564870/58911951-ddda4e00-86cd-11e9-9ebd-39ce6c1dc7d4.png)

**colorls**
![Screen Shot 2019-06-04 at 1 37 05 PM](https://user-images.githubusercontent.com/4564870/58911960-e16dd500-86cd-11e9-841e-0844dfbd7e21.png)

**gls (GNU coreutils on mac) version 8.30**
![Screen Shot 2019-06-04 at 1 45 21 PM](https://user-images.githubusercontent.com/4564870/58912515-12023e80-86cf-11e9-91f1-70d386a5d20b.png)

for example note that with colorls it doesn't show that `fun` currently has `4` hard links on the file

It would be nice if colorls showed the same info as BSD ls. Not sure if this information was left out intentionally. 

I couldn't find any relevant issues or PRs for this. I am not a Ruby expert by any means but I could probably try helping with an implementation if the maintainers are too busy. Thanks!

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [X] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Hi @alejandrogarciasalas,

thanks for the report. It shouldn't be too hard to code this up, a PR would be welcome! :wink:
