### ISSUE TITLE
Extension: Add an option to disable printing metadata / extra information

### ISSUE THREAD

**Issue by kaustubhhiware** [athityakumar/colorls#3]
There should be an option, similar in idea to `ruby colorls.rb --simple` os something equivalent.
 
![image](https://user-images.githubusercontent.com/11318551/27735015-1c01d4a2-5dbb-11e7-9c5e-10ca73a7082c.png)

This would ensure that the lines below, and including `Found 6 contents in directory` are not printed.

**Comment by athityakumar** [comment]
Added `--report` flag option to show the metadata.
