### ISSUE TITLE
Can't use in a Ruby project

### ISSUE THREAD

**Issue by trivett** [athityakumar/colorls#30]
Great project, definitely snazzes up a dull terminal. I was just about to alias ls to lc when i  ran into trouble once i tried this inside of a Ruby (rails) project. 

It looks like it needs the colorize gem in the bundle to work and I even threw it into the gemfile to see if that works, no luck. 
Here is my error: 

```
/Users/vincent/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- colorize (LoadError)
	from /Users/vincent/.rbenv/versions/2.2.6/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/vincent/bin/colorls/colorls.rb:3:in `<main>'
```
Any idea how to fix? 

Much appreciated!

**Comment by athityakumar** [comment]
@trivett - Thanks for filing this. It seems to be working with `.rvm` and bundler, but I haven't tested on `.rbenv` yet. 😄 

Can you please try the below and get back?

Option 1.
```sh
gem uninstall colorls
gem install colorls
rbenv rehash
rehash
``` 

Option 2. Add dependencies like `colorize` to a global `rbenv-gemset`.

**Comment by trivett** [comment]
Option 1 worked like a charm, thank you! If I'm not the only one it might be worth putting in the readme but probably fine as is. Cheers!

**Comment by athityakumar** [comment]
@trivett - I'm glad it worked. Would you be interested to add this in the README.md (Installation section > Between points 3 & 4, in italicized font) and send a PR?

**Comment by trivett** [comment]
No problem!
