### ISSUE TITLE
Hex Colors

### ISSUE THREAD

**Issue by SealedJoy** [athityakumar/colorls#312]
- Type of issue :
  - [x] Feature request
First of all, great project! Thanks for the time and effort you have shared!

I'd really like to be able to import hex color codes directly into the yaml file for reading by rainbow, this would allow theme compatibility with other tools such as pywal.

So far i've tried stringifying and dropping the leading # from the hex string etc but the dark_colors.yaml file seems to only accept rainbow color name descriptions. Apologies if i have missed something, any help is gladly appreciated.

**Comment by Falkgaard** [comment]
I second this request. Either 0-255 colours or hex colours, please! Rainbow colour names are nothing but a pain in the ass not to mention way too limited when it comes to synchronizing with other themes (custom themed nVim NERDtree directory and file colours in my case).

Awesome project, by the way!

**Comment by bigpick** [comment]
I tried implementing this in that linked PR above; it accepts hex values for color if you pass them in as a quoted in the yaml file. Also continues to work with the existing X11/Ansi color names.
