### ISSUE TITLE
Unable to install on Mac

### ISSUE THREAD

**Issue by rishabhdeepsingh** [athityakumar/colorls#313]
### Description
```
sudo gem install colorls                                                                                                                   
Building native extensions.  This could take a while...
ERROR:  Error installing colorls:
ERROR: Failed to build gem native extension.

current directory: /Library/Ruby/Gems/2.3.0/gems/clocale-0.0.4/ext/clocale
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20190924-13437-rywi6o.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h
extconf failed, exit code 1
Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/clocale-0.0.4 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/clocale-0.0.4/gem_make.out
```
- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [X] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Hi.

You need to install Ruby including its development files first. You'll also need a C compiler and the `make` tool in order to build the native extensions used by colorls.

On OSX, it's probably easiest to use homebrew.

**Comment by rishabhdeepsingh** [comment]
- [x] HomeBrew also installed
 - [x] Ruby installed
 - [x] C compiler is also installed `gcc-9` and `clang`
Still getting the same error.

**Comment by avdv** [comment]
So, the error still is
> can't find header files for ruby at `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h`

Right?

Then you're using the wrong Ruby version. Probably because you use `sudo gem ...` which gives you the ruby version of the root user, not the one you installed with homebrew. Try `sudo $(which gem) ...`, but make sure you have set up your `PATH` correctly, so that `ruby --version` returns the correct number. You should preferably use Ruby 2.6.

**Comment by avdv** [comment]
Side note: I don't understand why people always try to install things with sudo / into the system. Simply try running `gem install --user-install colorls` - this will install the binary into `~/.gem/ruby/2.?/bin`. You only need to setup your shell to add this to your `PATH` and you're done.
