### ISSUE TITLE
Case insensitive directory matching

### ISSUE THREAD

**Issue by maxwellainatchi** [athityakumar/colorls#325]
### Description
It would be nice if (especially on case-insensitive file systems like APFS) directory names were checked case-insensitively. This already seems to be the default behavior for file extensions, so it would just be making directories match the existing functionality.

- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Hi, this is indeed a misbehavior of some BSDs and OSX. This kind of thing works out of the box on Linux, no matter which file system you use. See https://github.com/athityakumar/colorls/issues/235 for a discussion.

**Comment by avdv** [comment]
BTW, try `--sort=none` which should use the underlying file system sorting, which *might be* what you want.

**Comment by maxwellainatchi** [comment]
@avdv Ah sorry, I meant in the color/icon configs. e.g. if I define an icon for `Pods`, it should also work for `pods`. I'm not a ruby dev, and I'm not very familiar with the codebase, but I believe the fix is in https://github.com/athityakumar/colorls/blob/master/lib/colorls/core.rb#L315. The matching behavior for file extensions that I mentioned is https://github.com/athityakumar/colorls/blob/master/lib/colorls/core.rb#L321

**Comment by avdv** [comment]
Oh, yes. I completely misunderstood.

**Comment by maxwellainatchi** [comment]
Is there any update on this? should be a pretty simple change

**Comment by maxwellainatchi** [comment]
@avdv I believe it's a 1-liner, so I just submitted a PR myself: https://github.com/athityakumar/colorls/pull/348
