### ISSUE TITLE
Icons not displaying in Hyper

### ISSUE THREAD

**Issue by jakeashcraft** [athityakumar/colorls#328]
### Description

I can't seem to get font icons to render in Hyper. Following the documentation, it says to install the patched fonts _Install the patched fonts of powerline nerd-font and/or font-awesome_. However, I don't see any fonts in the patched list that match those names. The Anonymice Nerd Font is a Powerline but didn't work. I also tried Hack and Droid Sans but those didn't work either. I am assuming there is a config for setting the font to use? My apologies if this isn't a valid issue, I'm sure I am doing something wrong.

I originally had ZSH and OH-MY-ZSH installed but uninstalled OH-MY-ZSH. Is it advisable to uninstall everything (ZSH, Colorls, fonts, etc) including my .zshrc file and start over?

<img width="230" alt="missing-font-icons" src="https://user-images.githubusercontent.com/3633753/71751817-7098c200-2e42-11ea-986c-fb95736d7081.png">

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [x] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
> However, I don't see any fonts in the patched list that match those names.

You can choose *any* of the fonts from nerdfonts. All of them are patched powerline / font-awesome fonts.

> The Anonymice Nerd Font is a Powerline but didn't work. I also tried Hack and Droid Sans but those didn't work either. I am assuming there is a config for setting the font to use?

Yes, somewhere you need to set the font in your config for hyper (`fontFamily` setting). It is important to select a **nerd** font not the original unpatched font (if happen to have any of these installed), otherwise it won't work.

If you are using homebrew, you can install a font with e.g. `brew cask install font-hack-nerd-font`, then log out and back in.

> I originally had ZSH and OH-MY-ZSH installed but uninstalled OH-MY-ZSH. Is it advisable to uninstall everything (ZSH, Colorls, fonts, etc) including my .zshrc file and start over?

No.

**Comment by jakeashcraft** [comment]
OK, that is good to know that any of the fonts would work. However, the font is installed and hyper is configured to use it but still can't get it to work. 

Here is my hyper config where I added the Nerd Font.

<img width="771" alt="hyper-config" src="https://user-images.githubusercontent.com/3633753/71773932-8a620400-2f2b-11ea-95fd-77787af0387d.png">

Font is installed but icons still do not show.

<img width="614" alt="font-installed" src="https://user-images.githubusercontent.com/3633753/71773935-91891200-2f2b-11ea-8849-2d82406f41dd.png">

**Comment by avdv** [comment]
> Font is installed but icons still do not show.

Did you log out, log back in? Can you select the nerd font in other applications using a font selection dialog? (ie. is the font known by the graphics system?)

I just tried with Hyper 2.1.2 and it worked without changing the configuration at all. Of course, I have the nerd fonts properly installed.. :smirk:

**Comment by jakeashcraft** [comment]
Thanks, that helped me get on the right track. I was able to select the font in iTerm and the icons started working so I knew the fonts were installed properly. Next I messed around with the font configuration in the hyper config file and got it working.

Here is my config.

<img width="332" alt="font-update" src="https://user-images.githubusercontent.com/3633753/71783523-81b21200-2fad-11ea-8e1f-18c076683a98.png">

And now:

<img width="420" alt="icons-working" src="https://user-images.githubusercontent.com/3633753/71783524-8a0a4d00-2fad-11ea-87e6-523303474332.png">

Thanks for all your help!

**Comment by Alfian5229** [comment]
![Screen Shot 2020-04-22 at 19 34 10](https://user-images.githubusercontent.com/28615224/79982287-45f57680-84d0-11ea-8809-5f7489391a88.png)
it say not exists, how i install it?

**Comment by avdv** [comment]
@Alfian5229 did you follow the [instructions](https://github.com/Homebrew/homebrew-cask-fonts#lets-try-it) ? Did you run `brew tap homebrew/cask-fonts` ?

**Comment by alfianrehanusa** [comment]
Oh i see, thanks for your help
