### ISSUE TITLE
.git folder should be a more generic git icon rather than GitHub, Inc's logo

### ISSUE THREAD

**Issue by trivett** [athityakumar/colorls#33]
Personally rubs me the wrong way that Git is conflated with Github in the minds of many.

Suggest using [this icon](http://fontawesome.io/icon/code-fork/) perhaps.

**Comment by athityakumar** [comment]
I tried out quite a few icons, but none of them really felt like a 'git directory logo' (ie, they were tiny and not much visible). Hence, I had to compromise with github logo.

Can you attach a screenshot of `lc` with that icon? (Just to make sure it's visible and not too tiny)

**Comment by kaustubhhiware** [comment]
Totally agree with @trivett's views about this. The discussions on reddit also pointed this out, but the sad thing is the available icons were not easily distingishable.

**Comment by trivett** [comment]
👍  Will take a look in a bit

I do not work for Bit Bucket fwiw :)

**Comment by trivett** [comment]
Taken on 2015 MacBook Pro 16 pt Ubuntu Mono in iTerm2:

1) 
<img width="375" alt="screen shot 2017-07-06 at 3 03 53 pm" src="https://user-images.githubusercontent.com/1496845/27928270-8a5fcb0c-625c-11e7-99e6-ba3481363c3d.png">

2) 
<img width="184" alt="screen shot 2017-07-06 at 3 05 58 pm" src="https://user-images.githubusercontent.com/1496845/27928318-b76f9cc6-625c-11e7-8aa8-bc84c5b41f69.png">

**Comment by athityakumar** [comment]
@trivett - Also, you can consider some icons from [nerdfonts](https://nerdfonts.com/).
@kaustubhhiware - Sadly, that's true. They didn't investigate the reason behind why the `.git/` folder has a `github` icon - they just assumed that the OP didn't know that git & github are different.  😢

**Comment by trivett** [comment]
Yep those two are from nerdfonts.

**Comment by athityakumar** [comment]
Hmm, any suggestion for other alternate icons for `.git/`?

**Comment by pimlottc** [comment]
Why not use the same icon that is being used for .gitignore?

**Comment by athityakumar** [comment]
@pimlottc - LGTM. How about others?

**Comment by ryanoasis** [comment]
I was going to suggest `e5fb` but at a typical term font size probably too small to even know what it is. Maybe it's time to create some more glyphs? :smirk:

**Comment by athityakumar** [comment]
> I was going to suggest e5fb but at a typical term font size probably too small to even know what it is.

For now, I think we can workaround with` f1d3`.

> Maybe it's time to create some more glyphs?

(*Fanboy mode on, after seeing this suggestion from the maintainer of Nerd Fonts*) 😉 
Yes please. There can never be more of glyphs. 😄
