### ISSUE TITLE
Icons are too small

### ISSUE THREAD

**Issue by EddieEldridge** [athityakumar/colorls#332]
### Description

![image](https://user-images.githubusercontent.com/22448079/71973650-59bdeb00-3207-11ea-9cef-2c173207435a.png)

After installing colorls and installing the nerd-fonts by downloading the repo and running the install script, my icons are **very small** for some reason. I'm using the Gnome Terminal if that helps.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [X ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by EddieEldridge** [comment]
I enabled custom fonts and changed the font to a NerdFont that was non/bold italic. The size of the icons is dependent on your font. Play around with different font types and you will see the icons change.

**Comment by jadia** [comment]
As @EddieEldridge suggested changing the font to `Hack Nerd Font Regular` fixed the issue for me in Ubuntu 20.04.
