### ISSUE TITLE
missing git-status icon for directories (v1.3.1)

### ISSUE THREAD

**Issue by draptik** [athityakumar/colorls#334]
### Description

- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

After upgrading to colorls 1.3.1 the git-status icons for directories are missing. The git-status icon is displayed correctly for files.

Steps to reproduce:

```sh
mkdir colorls-stuff
cd colorls-stuff
touch test.txt
mkdir foo
touch foo/bar.txt
git init
git add .
git commit -am"initial commit"
colorls -l --gs
cd foo
colorls -l --gs
```
Note the missing git-status icon for directory `foo` in screenshot below.

![Screenshot from 2020-01-17 07-33-11-colorls-bug](https://user-images.githubusercontent.com/313058/72589502-c027c500-38fb-11ea-8161-8c5e433164cf.png)

- OS: Arch Linux
- colorls installed via pacman (Source: https://aur.archlinux.org/packages/ruby-colorls/)

**Comment by avdv** [comment]
Thanks for the report, I'll have a look into this as soon as I find some time.
