### ISSUE TITLE
Runtime error in vim terminal

### ISSUE THREAD

**Issue by RabbitJazz** [athityakumar/colorls#335]
### Vim terminal issue.

- Relevant Issues : ~
- Relevant PRs : ~
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

Colorls works in the terminal properly although I have encountered several issues regarding Nvim/vim built in terminal.
This error is presented for any command I try to run : 

<img width="624" alt="screenshot_2020-01-19_15-06-27" src="https://user-images.githubusercontent.com/50245184/72681555-6aa31200-3acd-11ea-9293-5f431f81d273.png">

If the image won't appear : 

```
Traceback (most recent call last): 
4: from /usr/local/bin/colorls:23:in `<main>' 
3: from /usr/local/bin/colorls:23:in `load'
2: from /Library/Ruby/Gems/2.6.0/gems/colorls-1.3.1/exe/colorls:6:in `<top (required)>' 
1: from /Library/Ruby/Gems/2.6.0/gems/colorls-1.3.1/lib/colorls/flags.rb:41:in `process'
/Library/Ruby/Gems/2.6.0/gems/colorls-1.3.1/lib/colorls/flags.rb:41:in `setlocale': error calling `setlocale(LC_COLLATE, "")` (RuntimeError)`

```

Help will be appreciated :)

**Comment by avdv** [comment]
Probably similar to #204 resp. #203.

What is the output of `locale` in your VIM terminal?

**Comment by RabbitJazz** [comment]
LANG="en_IL"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

**Comment by avdv** [comment]
That seems to be an invalid locale on your system. Try setting `LC_CTYPE` to `en_IL.UTF-8`... 

Also, compare the output of `locale` inside a normal terminal to the one from VIM term.
