### ISSUE TITLE
git-status shows a "green tick" for everything.

### ISSUE THREAD

**Issue by amirashabani** [athityakumar/colorls#336]
- Type of issue : 
  -  Bug in existing feature

When I use `colorls --gs`, it shows a green tick for files that have been modified or even created recently. 

![lc -af --gs](https://user-images.githubusercontent.com/23696447/72907013-6df60200-3d48-11ea-8757-cd363c332910.png)

Here's my system's info, if it's relevant:

![neofetch](https://user-images.githubusercontent.com/23696447/72907153-ac8bbc80-3d48-11ea-94fd-9034e82f161c.png)

**Comment by draptik** [comment]
Just noticed this bug.
Maybe related to #334 ?

**Comment by avdv** [comment]
Hey, I have released 1.3.2 which just hit rubygems, so `gem update colorls` and that should be fixed. Sorry it took me so long.
