### ISSUE TITLE
Cannot list files/directories with spaces using `-l` flag

### ISSUE THREAD

**Issue by SturmB** [athityakumar/colorls#338]
### Description

Thanks for opening this issue. Add a brief description of what this issue is, and how to recreate it. Do tag the relevant issue(s) and PR(s) below. If required, add some screenshot(s) to showcase the issue.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

So it seems that running `colorls -l` in any directory that contains entries with spaces in them returns an error message:
```
Permission denied @ rb_readlink
```
The command works fine **without** the `-l` flag, but not **with** it.

This is most relevant on WSL because Windows has many directories with spaces in their names.

Let me know if screenshots are needed, please let me know; I will gladly provide them. In the meantime, here's an example of the output from `pwd`, then `colorls`, then `colorls -l` (The icons are obviously not going to render in GitHub):
```
Γ¥» pwd
/c/Users/<username>
Γ¥» colorls
    ∩à¢  0-byte_files.flt
    ∩äò  3D Objects/
    ∩äò  AppData/
    ∩à¢  Application Data
    ∩äò  Contacts/
    ∩à¢  Cookies
    ∩äò  Creative Cloud Files/
    ∩äò  Desktop/
    ∩äò  dev/
    ∩äò  dircolors-solarized/
    ∩äò  Documents/
    ∩äò  dotfiles/
    ∩äò  Downloads/
    ∩äò  Dropbox/
    ∩äò  eclipse/
    ∩äò  Evernote/
    ∩äò  Favorites/
    ∩äò  fonts/
    ∩äò  Homestead/
    ∩äò  Job Temp/
    ∩äò  karlin-mintty-colors-solarized/
    ∩äò  Links/
    ∩à¢  Local Settings
    ∩äò  mavnn-mintty-colors-solarized/
    ∩äò  MicrosoftEdgeBackups/
    ∩äò  Music/
    ∩à¢  My Documents
    ∩à¢  NetHood
    ∩äò  Nintendo Saver/
    ε£ÿ  node_modules/
    εÿò  nsswitch.conf
    ∩à¢  NTUSER.DAT
    ∩à¢  NTUSER.DAT{740a8f7a-8deb-11e9-90c1-a114d0226922}.TM.blf
    ∩à¢  NTUSER.DAT{740a8f7a-8deb-11e9-90c1-a114d0226922}.TMContainer00000000000000000001.regtrans-ms
    ∩à¢  NTUSER.DAT{740a8f7a-8deb-11e9-90c1-a114d0226922}.TMContainer00000000000000000002.regtrans-ms
    ∩à¢  ntuser.dat.LOG1
    ∩à¢  ntuser.dat.LOG2
    ∩à║  ntuser.ini
    ∩à¢  ntuser.pol
    ∩äò  OneDrive/
    ∩äò  Pictures/
    ∩à¢  PrintHood
    ∩à¢  Recent
    ∩äò  Saved Games/
    ∩äò  Searches/
    ∩à¢  SendTo
    ∩äò  Sites/
    ∩à¢  Start Menu
    ∩à¢  Templates
    ∩äò  Videos/
    ∩äò  winpty/
    ∩à¢  wslbridge2.exe.stackdump
    εê₧  yarn.lock
Γ¥» colorls -l
/c/Users/<username>: Permission denied @ rb_readlink - /c/Users/<username>/Application Data
```

**Comment by avdv** [comment]
I doubt that it has anything to do with spaces. Especially since it said "permission denied"... The point is simply that `-l` tries to resolve symbolic links, which apparently failed for the `Application Data` folder.

I'll look into this when I found some time. But don't expect wonders, given that I don't have Windows box and thus colorls is not really tested on Windows.

**Comment by avdv** [comment]
Version 1.3.3 is out with a fix.

**Comment by SturmB** [comment]
Yep, that takes care of it to my satisfaction. It now displays those junctions (Windows version of a symbolic link) as an ellipsis. But at least it does recognize that it's a link. 😊

![ConEmu64_PhkJA5RlRp](https://user-images.githubusercontent.com/6216224/73545333-225aec80-4409-11ea-8f2b-4cc168def1c4.png)
