### ISSUE TITLE
Icon didn't display.

### ISSUE THREAD

**Issue by RathanakSreang** [athityakumar/colorls#34]
I did install `gem install colorls`.
Then I run `lc` it shows the list of my files and folders with come color but the icon is not working(` `).
Does anyone know what I did wrong?

**Comment by athityakumar** [comment]
@RathanakSreang - Thanks for reporting this issue. I think you missed the step 2 of installation. Please install the patched `nerd-font` font and try `lc`. 😄

**Comment by bgold0** [comment]
Would anyone care to give any guidance on how to actually install the fonts. Step 2 isn't very informative

**Comment by athityakumar** [comment]
@bgold0 - Regarding the nerd-font installation, please read the README [here](https://github.com/ryanoasis/nerd-fonts). 😄

**Comment by bgold0** [comment]
I did Option 2 for Mac OS X and still get question marks for the icons

**Comment by athityakumar** [comment]
@bgold0 - Hmm, are you using iTerm2?

**Comment by cknoxrun** [comment]
I'm in the same boat, just using plain OSX Terminal

**Comment by gk7279** [comment]
I fixed the same issue by opening terminal preferences -> text -> choosing nerd-font.

**Comment by athityakumar** [comment]
@cknoxrun @bgold0 @RathanakSreang - Did you try the fix suggested by @gk7279 for `Terminal.app` and the one suggested in README for iTerm2?

**Comment by cknoxrun** [comment]
@athityakumar yep that did it, thanks!

**Comment by bgold0** [comment]
@gk7279's comment worked perfectly

**Comment by athityakumar** [comment]
Glad to hear, @bgold0 and @cknoxrun. How about you, @RathanakSreang? Would one of you be interested in adding this to the README? 😄

**Comment by RathanakSreang** [comment]
@athityakumar 
It working fine now.
Awesome.
