### ISSUE TITLE
Missing year in long format

### ISSUE THREAD

**Issue by kakulukia** [athityakumar/colorls#346]
### Description

Not having the year if the file is older than one year is hiding some interesting information.
Default format for Dates is `Mon Dec  3` which is cool for everything newer than 1 year, but after that ithink another format would make more sense.

What about `Dec 3 2018`?

- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Could you illustrate what you mean?

For me, long listing shows like this:
```console
  rwxr-xr-x  1  claudio  1000      2 KiB  Mon Apr 30 13:29:19 2018    files/
  rwxr-xr-x  1  claudio  1000    138 B    Wed Sep 25 14:27:17 2019    logs/
  rwxr-xr-x  1  claudio  1000    126 B    Wed Mar  4 10:28:05 2020    codegen/
  rwxr-xr-x  1  claudio  1000    268 B    Wed Mar  4 17:25:26 2020    conf/
```
The year is right there, no?!

And which version of colorls are you using?

**Comment by kakulukia** [comment]
I was distracted by the time and not expecting a year after that. 🤦‍♂️
Now i actually feel a lil bit ashamed, raising that ticket ..

But maybe - to give it a lil meaning- what about another color setting for stuff thats older than a year?

**Comment by avdv** [comment]
> But maybe - to give it a lil meaning - what about another color setting for stuff thats older than a year?

I think we also have that already, there is some color difference for recent files, IIRC. Just don't know where the cut off is, maybe half a year... ?!

**Comment by avdv** [comment]
Actually, there is a different color if it's less than an hour, or if it's less than a day old.

**Comment by kakulukia** [comment]
Yes, I know those two. That's really cool. 
Maybe it also makes sense to mark really old stuff differently. 
I will also be fine with just closing the ticket and remember where to find the year. 😁
