### ISSUE TITLE
Total break in Fedora 32 Beta

### ISSUE THREAD

**Issue by hhlp** [athityakumar/colorls#349]
### Description

Thanks for opening this issue. Add a brief description of what this issue is, and how to recreate it. Do tag the relevant issue(s) and PR(s) below. If required, add some screenshot(s) to showcase the issue.

- Relevant Issues : (none)

Yes

- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

### NOTE

```
❯ LANG=C colorls
Traceback (most recent call last):
        2: from /usr/share/gems/gems/abrt-0.3.0/lib/abrt.rb:7:in `block in <top (required)>'
        1: from /usr/share/gems/gems/abrt-0.3.0/lib/abrt/handler.rb:10:in `handle_exception'
/usr/share/gems/gems/abrt-0.3.0/lib/abrt/exception.rb:16:in `executable': undefined local variable or method `backtrace' for nil:NilClass (NameError)
Traceback (most recent call last):
        10: from /usr/local/bin/colorls:23:in `<main>'
         9: from /usr/local/bin/colorls:23:in `load'
         8: from /home/hhlp/.gem/ruby/gems/colorls-1.3.3/exe/colorls:4:in `<top (required)>'
         7: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
         6: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
         5: from /home/hhlp/.gem/ruby/gems/colorls-1.3.3/lib/colorls.rb:9:in `<top (required)>'
         4: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
         3: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
         2: from /usr/local/share/gems/gems/clocale-0.0.4/lib/clocale.rb:15:in `<top (required)>'
         1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require': libruby.so.2.6: cannot open shared object file: No such file or directory - /usr/local/lib64/gems/ruby/clocale-0.0.4/clocale/clocale.so (LoadError)
``` 

Regards.,

**Comment by avdv** [comment]
Fedora 32 probably uses Ruby 2.7 but you have installed colorls for Ruby 2.6. Every time you change your ruby interpreter, you have to re-install colorls.

**Comment by hhlp** [comment]
same thing:

What I tried?

1. Uninstall it and Installing Again
2. Update

❯ gem list | grep colorls
colorls (1.3.3)

Regards.,

**Comment by avdv** [comment]
colorls depends on a few native extensions which need to rebuild too. I guess installing gems system wide is a bad idea since these are bound the the system Ruby, and everything breaks down when this is changed.

Basically, wipe out your `/usr/local/share/gems/gems/` and install again. Or better yet, just install to your user gem folder and add the gem dir to your `PATH`:
```
gem install --user-install colorls
PATH=$PATH:$(ruby -e 'puts Gem.bindir') # add this to your shell init file
```

**Comment by hhlp** [comment]
I did it

```
gem install --user-install colorls
```

1. Generate a bin directory in my home folder and I would like to about it
2. execute colorls inside `\home\hhlp\bin` directory and get same problem

Regards.,

**Comment by avdv** [comment]
I don't really understand. Could you show the complete session? Ie. which commands you ran and what the output of the commands was.

Note that you still have to remove the old colorls command in order for it to not interfere with the user installed one.

**Comment by jorge-romero** [comment]
Still not working with the just released Fedora 32

Traceback (most recent call last):
        10: from /home/xxxxxx/bin/colorls:23:in `<main>'
         9: from /home/xxxxxx/bin/colorls:23:in `load'
         8: from /home/xxxxxx/.gem/ruby/gems/colorls-1.3.3/exe/colorls:4:in `<top (required)>'
         7: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
         6: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
         5: from /home/biterchus/.gem/ruby/gems/colorls-1.3.3/lib/colorls.rb:9:in `<top (required)>'
         4: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
         3: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
         2: from /usr/local/share/gems/gems/clocale-0.0.4/lib/clocale.rb:15:in `<top (required)>'
         1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:92:in `require': libruby.so.2.6: cannot open shared object file: No such file or directory - /usr/local/lib64/gems/ruby/clocale-0.0.4/clocale/clocale.so (LoadError)

**Comment by avdv** [comment]
You still have the old clocale gem installed under /usr/local which is incompatible with your current Ruby installation. You have to remove all of the old Ruby extensions *first*, then reinstall colorls.

**Comment by jorge-romero** [comment]
Thanks, removing that gem, reinstalling colorls and executing 
`sudo gem pristine clocale`
worked for me.
