### ISSUE TITLE
Make symlinks visible with the -l option

### ISSUE THREAD

**Issue by mathiasuhl** [athityakumar/colorls#35]
I like to replace my ls with lc but its missing the option to show the target of a symlink. 
like "ls -l " test.rb -> mydir/test_v1.php

**Comment by athityakumar** [comment]
Hey @mathiasuhl, thanks for filing this issue. But I feel that this use-case of symlinks might be a tad bit less frequently used by the community. Anyways, are you sure it's the `-r` flag?

**Comment by athityakumar** [comment]
@mathiasuhl - Can you please confirm on whether symlimks are shown with `lc -l` as per v0.1.5 of `colorls` gem? To update to the latest gem version, just `gem update colorls`. 😄

**Comment by GladOSkar** [comment]
No they aren't. Shouldn't bee too hard though.

**Comment by GladOSkar** [comment]
Maybe i'll do it in the next few days

**Comment by athityakumar** [comment]
Great, I'm assigning this issue to you @GladOSkar 😄

**Comment by GladOSkar** [comment]
What about -r / --report? Should that or this be renamed?

**Comment by athityakumar** [comment]
@GladOSkar - Let `--report` be as it is. Use `-r` for symlinks.

**Comment by athityakumar** [comment]
@GladOSkar : How about using `-i` / `--info` to report, and `-r` for symlinks?

**Comment by GladOSkar** [comment]
@athityakumar seems more logical to me.

**Comment by GladOSkar** [comment]
I rethought: ls shows symlinks by default with `-l`.  I think that is more suitable here

**Comment by athityakumar** [comment]
@GladOSkar @mathiasuhl - Can this issue be closed now?

**Comment by GladOSkar** [comment]
IMO yes

**Comment by athityakumar** [comment]
@mathiasuhl - This feature has been added with PR #77, try updating `colorls`.  Closing this issue now, feel free to re-open this issue if required. 😄
