### ISSUE TITLE
Font Icons & Linux

### ISSUE THREAD

**Issue by define-private-public** [athityakumar/colorls#36]
Hi.  I'm trying to run this on Linux.  I'm a little stuck at the install line that says "Install the patched fonts of powerline nerd-font and/or font-awesome."  Can you give some better instructions?

Also, (at least on Linux) the `lc` command is already taken by the `Mono Licnese Compiler` if you have Mono installed.  This may be an issue for some others.

**Comment by athityakumar** [comment]
Hey @define-private-public! Thanks for filing this issue. Interesting GitHub username, by the way.
 😄 

- Regarding the nerd-font installation, read the README [here](https://github.com/ryanoasis/nerd-fonts).

- Regarding the `lc` command clash, please try if this works :
```sh
echo $(which lc) # gives path to lc
mv path/to/bin/lc path/to/bin/renamed_lc # renamed_lc is the new lc command name
```

This should definitely be added to the README though. Would you like to contribute?

**Comment by define-private-public** [comment]
Colorls is overriding the `lc` of Mono.  IMO, the command should be changed to something like `colorls`.  And then tell users they can modify their `.bashrc` files and add `alias lc='colorls'`.  Luckily on the machine I'm on right now, I don't use Mono for any development, but I'm not sure what happens on other systems.

I think that nerd-font step should be written out in the README too.  Thanks.

**Comment by athityakumar** [comment]
Agreed. Will correct this v0.1.2 for sure.

**Comment by athityakumar** [comment]
@define-private-public - Done. Try reinstalling v0.1.3. 😄 

```sh
gem uninstall colorls
gem install colorls
colorls
```

**Comment by define-private-public** [comment]
Thanks!

the README needs to be updated though to reflect the command changes.

**Comment by athityakumar** [comment]
Isn't it updated?

**Comment by define-private-public** [comment]
No.  Taken from the top section:

"- Just `lc` : Prints all directories, files and dotfiles in current directory."

A good old search and replace should fix this though.

**Comment by athityakumar** [comment]
I mean, doesn't the `Recommended configurations` take care of this? Or is it definitely required to completely remove `lc` from README? 😕

**Comment by define-private-public** [comment]
It causes a little confusion IMO, since "Recommend configuration," comes after the first example usages of `lc`.

Think about this this way:  Someone installs the software with only reading the first bits and tries running `lc`.  They will see nothing unless they knew to read the entire README; which doesn't always happen.  You could move that alias up, or do the search and replace.

Right now I have it as `alias ls='colorls'` in my .bashrc.
