### ISSUE TITLE
Icon Size/ Padding Issue

### ISSUE THREAD

**Issue by AnirvanB** [athityakumar/colorls#376]
### Description

I use *colorls* on both Mac and Linux. On Linux (Fedora), I encountered this peculiar problem where the item's icon size appears to be too small and padding/ margin from the text seems a bit excessive. 

Terminal App: Terminal/ Tilix (VTE)
Shell: ZSH 5.8 with [Powerlevel10k](https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k)
Font: Meslo Nerd Font patched for Powerlevel10k (set to size 9pt)

![Screenshot from 2020-08-01 14-47-40](https://user-images.githubusercontent.com/44327359/89098519-0ced6c00-d406-11ea-9199-3a8c42139905.png)

I don't face this issue on Mac. Also, have tried playing around with font size, it hasn't helped. Anyway this can be fixed?

- Type of issue :
  - [ ] Installation
  - [ ] Feature request
  - [x] Font-related (Mostly)
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by AnirvanB** [comment]
Issue can be re-produced with: 
* Bash
* Vanilla ZSH

Icon size issue exists with equivalent apps like [exa](https://github.com/ogham/exa) too, but the padding issue doesn't.

![Screenshot from 2020-08-01 22-19-41](https://user-images.githubusercontent.com/44327359/89106218-9d976c80-d445-11ea-802c-2a690098c483.png)

Wondering if this qualifies as a bug, or is an isolated issue.

**Comment by avdv** [comment]
Hi.

I am also using a VTE based terminal and I don't see such behavior.

Currently, I'm on vacation and will be AFC the next weeks so I cannot check my settings.

**Comment by AnirvanB** [comment]
@avdv - Hi Claudio, Thanks for the response! Enjoy your vacay! I'll follow-up in about ~2 weeks.

**Comment by AnirvanB** [comment]
**UPDATE**

Issue was with the font selection. I was using a mono font earlier. Once I switched to a non-mono font (Hack Nerd Regular) both *Icon Size/ Padding* Issue got rectified.

![Screenshot from 2020-08-17 00-26-36](https://user-images.githubusercontent.com/44327359/90355087-f16e9c00-e068-11ea-9b75-4958124d4b97.png)

However, issue still persists on other terminal. Icon size for some of the records are way too small.

![Screenshot from 2020-08-17 00-26-07](https://user-images.githubusercontent.com/44327359/90355129-19f69600-e069-11ea-8fdf-514715a2110f.png)

**Comment by avdv** [comment]
Closing, as the issue seems resolved.
