### ISSUE TITLE
error when calling setlocale in Neovim terminal

### ISSUE THREAD

**Issue by devstefancho** [athityakumar/colorls#387]
### Description

I'm Neovim user and when I try `ls` in neovim terminal
I got this warning,(when I use Iterm2, no errors)
This error doesn't make a significant error, but this message makes me a little nervous, so I want to resolve this issue

What I did for this
1. update colorls
2. uninstall and re-install

Here's below, in nvim terminal and warning message, In case of not displaying image, 
```
WARN: error calling  `setlocale(LC_COLLATE, "")`, check your locale settings
```
 is error message

<img src="https://user-images.githubusercontent.com/61320923/91868769-104b7000-ecb0-11ea-8220-862ba8f9d8f5.png" width="500" height="300"/>

I want to use this in vim terminal, please help me!
best regards,

- Relevant Issues : #203 
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Hi.

What's the output of `locale -a | grep en_KR` ? Are the locale settings the same in lterm2 and neovim terminal?

Are you sure you are using the latest version of colorls? What gives `colorls --version`?

**Comment by devstefancho** [comment]
so.. I've checked what you said,

> locale -a | grep en_KR

: output : nothing (both iterm2 and neovim terminal)

> colorls --version

: 1.4.2 

as far as I remember, I did not setup both terminal locale manually (so I don't know how to setup locale settings)
but I find different between iterm2 and nevoim locale

**in iterm2**
```
$ locale 
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
**in neovim terminal**
```
$ locale 
LANG="en_KR"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

is there any problem from this results??
thanks again.

**Comment by devstefancho** [comment]
This issue is solved,
I changed my neovim locale language 

add `language en_US` to my `.config/nvim/init.vim'
after that, locale output in neovim terminal
```
$ locale
LANG="en_US"
LC_COLLATE="en_US"
LC_CTYPE="UTF-8"
LC_MESSAGES="en_US"
LC_MONETARY="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_ALL="en_US/UTF-8/en_US/en_US/en_US/en_US"
```
then when `ls` , error is gone.

thanks for your support

[reference](https://vi.stackexchange.com/questions/14429/why-is-my-neovim-not-in-english-and-how-do-i-force-it-to-be)
