### ISSUE TITLE
Support for -a / --all

### ISSUE THREAD

**Issue by define-private-public** [athityakumar/colorls#39]
Is there a way to do this?  a good 3/4 of my home directory are dot files.  Right now the output kind of pollutes my screen with a lot more files than I need to look at.

**Comment by athityakumar** [comment]
@define-private-public - Would a `-a` / `--all` flag work? This is yet to be implemented. 😄

**Comment by define-private-public** [comment]
I think that hiding dot files should be the default, and `-a/--all` to show everything.  Just like with regular ls.

**Comment by athityakumar** [comment]
Accepted. Renamed the issue. 👍

**Comment by athityakumar** [comment]
Added with commit 69ce52e1acc2f679b2800c781248835eaf6af813 and gem v0.1.4. 👍

**Comment by define-private-public** [comment]
Works for me

**Comment by define-private-public** [comment]
wait.  It should also show `.` and `..` too.

**Comment by athityakumar** [comment]
@define-private-public - Fixed with PR #75 , yet to be released (v0.1.6).

**Comment by athityakumar** [comment]
Released with v0.1.6. 😄
