### ISSUE TITLE
Could I customize how things show up in `-l` mode ?

### ISSUE THREAD

**Issue by mlch911** [athityakumar/colorls#395]
### Description
Could I customize how things show up in `-l` mode ?
For example, I don't want such a long time format. I just want something like `20-09-18 10:45`.
![screenshot](https://i.loli.net/2020/09/18/ERtwi4qzQnlfkUG.png)

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by fharper** [comment]
Would love to customize the time, but also be able to remove the hard links count.

**Comment by t-mangoe** [comment]
I tried implementing for this issue.
I added `--time-format` option. You can set the list time format in Ruby's Time#strftime format.

For example, `--time-format="%y-%m-%d %k:%M"`.
![スクリーンショット 2021-09-04 15 37 12](https://user-images.githubusercontent.com/22494246/132085458-3790bf32-8564-4336-946d-0b6c8b7021c4.png)

**Comment by t-mangoe** [comment]
@mlch911
Thank you for your good reaction.
If it is ok, I'm planning to add tests and then make a pull request.
(Maybe it may take some time. I'm glad if you could wait patiently.)

**Comment by avdv** [comment]
Thank you for working on this @t-mangoe!

Please note, when you create a PR, the command line option should match the GNU ls option:

```
--time-style=TIME_STYLE

The TIME_STYLE argument can be full-iso, long-iso, iso, locale, or +FORMAT. FORMAT is interpreted like in date(1).
```
So, it should look like this:
```console
$ colorls --time-style='+%y-%m-%d %k:%M'
```

**Comment by t-mangoe** [comment]
@avdv
Thank you for your comment!!
Ok, I'll change the option name into `time-style`.
