### ISSUE TITLE
Could not install on Ubuntu 20.4

### ISSUE THREAD

**Issue by Rawnly** [athityakumar/colorls#398]
### Description

Thanks for opening this issue. Add a brief description of what this issue is, and how to recreate it. Do tag the relevant issue(s) and PR(s) below. If required, add some screenshot(s) to showcase the issue.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [x ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation
---
```
Building native extensions. This could take a while...
ERROR:  Error installing colorls:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.7.0/gems/clocale-0.0.4/ext/clocale
/usr/bin/ruby2.7 -I /usr/lib/ruby/2.7.0 -r ./siteconf20200924-22271-o8nk7s.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

```

**Comment by avdv** [comment]
> You might have to install separate package for the ruby development
> environment, ruby-dev or ruby-devel for example.

Try `apt install ruby-devel` or something similar.

**Comment by Rawnly** [comment]
Fixed with

```sh
sudo apt install ruby-full
```

**Comment by yasonrails** [comment]
Fixed with

sudo apt install ruby-full
