### ISSUE TITLE
Working with options / flags

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/colorls#4]
`ls -l` works, but something like `lc -l` doesn't. Having this feature to highlight file formats in strings would be a great feature.

**Comment by athityakumar** [comment]
@kaustubhhiware - Can you confirm whether this is fixed on current master by pulling it? (as of commit 23d95fc5a1867d974f69169ae0e57c2119a8e28a)

That is, usage like `lc -al . ../ ~/`

**Comment by kaustubhhiware** [comment]
Umm, there is good news and bad news.
Good news: 
* Flags work
Bad news:
* I'm getting a warning previously unreceived: `colorls/core.rb:25: warning: Insecure world writable dir ~/.config in PATH, mode 040777`
* Why are all the listings only one per row ?

**Comment by athityakumar** [comment]
Understood. Previously, lc was only to work with options and hence it had custom indents and stuff. But now that I want lc to colorize any output of ls, it has to mimic it.

Currently, it splits by newline and then space to get all words. If word is file / directory, colorize. Else, just print.

This is the reason behind the issue #5 too. It somehow now has to be made to work without splitting with \n and space - and rather just do string manipulation on output of ls.

**Comment by athityakumar** [comment]
@kaustubhhiware - Just had a look at [this link](http://mywiki.wooledge.org/ParsingLs) and seems like it was a bad idea to try adding all ls flag features to lc. I think it'd be better to keep `lc` simple with just dirs support, rather than printing 1 file / line just for supporting flags. WDYT?

**Comment by kaustubhhiware** [comment]
Hmm, maybe just stick with whatever best you do. According to me, only two flags could be useful to someone:
* `lc -a`  to show hidden files
* `lc --simple` as suggested in #3  (This should be feasible since output of `ls` is not being parsed)

I don't think all flags need to be covered, for instance, if I were interested in more detailed information, I would just do `ls -l`, and not `lc -l`.

**Comment by athityakumar** [comment]
1. `lc` is automatically returning all dotfiles by default.
2. Yep, added this. Check the latest master (1fbd3a723b716ef20797b52781f10f07eff95e9e).

**Comment by kaustubhhiware** [comment]
Can confirm this as per commit `405b3f0`. Can close this issue now.

**Comment by athityakumar** [comment]
Thanks! Closing this issue now. 😄

**Comment by kaustubhhiware** [comment]
@athityakumar I think this needs to be known. 
The number of content names in different locations varies.

This seems intentional, since the number of listings per row seems to depend on the longest name in that folder. This is in no way an issue, but might as well check.

**Comment by athityakumar** [comment]
@kaustubhhiware - Currently, it doesn't depend on the longest name in the folder, but the longest in each column being shown. But sure, error handling is required. Or rather, proper logic to rule out the incorrect flags (so, except `--report` for now).
