### ISSUE TITLE
Icons not showing at all.

### ISSUE THREAD

**Issue by jinyongp** [athityakumar/colorls#406]
### Description

I'm using HyperTerm, so I added `Hack Nerd Font` to `fontFamily`  in `~/.hyper.js` but it didn't work.

How can I solve this problem?

![image](https://user-images.githubusercontent.com/21158729/96861496-23eca900-149f-11eb-9265-303a2e931573.png)

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [x] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
You have to configure your locale that unicode characters can be shown. What's the output of `locale`?

**Comment by jinyongp** [comment]
Oh. `LC_ALL` had been set to `C` in my locale config. So I just changed it to `en_US.UTF-8`. It works well. Thanks for your help.
