### ISSUE TITLE
If the directory contains Chinese file names, alignment errors will occur

### ISSUE THREAD

**Issue by Chdy** [athityakumar/colorls#416]
### Description

Thanks for opening this issue. Add a brief description of what this issue is, and how to recreate it. Do tag the relevant issue(s) and PR(s) below. If required, add some screenshot(s) to showcase the issue.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [*] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

![A8C92690-FEDF-4AFF-917E-CFB94EEB56CC](https://user-images.githubusercontent.com/20040948/99622941-11499d80-2a66-11eb-8d8a-1290051a7e91.png)

For each line, if Chinese appears on the left, then there will be an incorrect alignment on the right

**Comment by avdv** [comment]
Could you just copy and paste the output from your terminal please?! A screenshot is usually not helpful when trying to reproduce am issue.

**Comment by Chdy** [comment]
❯ ls
      124751F4-1062-4FBC-B519-E6B7051EEEAB.png       Style.synctex.gz       _minted-英文文献翻译/      毕业论文.out          英文文献翻译.aux
      Picture/                                       Style.tex              missfont.log         毕业论文.pdf          英文文献翻译.log
      Style.aux                                      Translate/             section/             毕业论文.tex          英文文献翻译.out
      Style.log                                      _minted-Style/         毕业论文.aux             毕业论文.toc          英文文献翻译.pdf
      Style.pdf                                      _minted-毕业论文/          毕业论文.log             毕业论文CJK.pdf       英文文献翻译.tex
![F3180749-2221-4C3F-B5B9-6566228D1E44](https://user-images.githubusercontent.com/20040948/99747461-858f4a00-2b15-11eb-8032-b9600db33c07.png)

**Comment by Chdy** [comment]
I don’t know why multiple spaces are combined into one in github. I copied the output into a file, hoping to display normally
[error.txt](https://github.com/athityakumar/colorls/files/5570766/error.txt)

**Comment by avdv** [comment]
The problem seems to be the width of the characters in your font. The kanji simply take more space than the roman characters, as it's not a truly mono-space font I guess.

GNU ls seems to circumvent this problem by using tabs to display the file names.
