### ISSUE TITLE
Can't see the icons despite installing all the relevant fonts

### ISSUE THREAD

**Issue by abhisheksha** [athityakumar/colorls#431]
Hi,

Despite following all the mentioned steps, I cannot get `colorls` to be working. The mini glyphs just do not display, I don't see any square box or anything indicating a missing font. It's empty. 

Here's the ruby version installed:
![Screenshot 2021-01-04 at 10 40 28 PM](https://user-images.githubusercontent.com/1282847/103560480-d8fb0300-4edd-11eb-85a8-702da3e4eb11.png)

I've downloaded the modified Meslo font, and I'm able to see glyphs such as `echo $'\ue62b'`
![Screenshot 2021-01-04 at 10 41 19 PM](https://user-images.githubusercontent.com/1282847/103560557-f760fe80-4edd-11eb-8124-6d3dba68c7a0.png)

Colorls has been installed.
![Screenshot 2021-01-04 at 10 41 58 PM](https://user-images.githubusercontent.com/1282847/103560615-0e9fec00-4ede-11eb-94a6-57d4f8852353.png)

Here are my iTerm2 settings:
![Screenshot 2021-01-04 at 10 42 36 PM](https://user-images.githubusercontent.com/1282847/103560675-25ded980-4ede-11eb-949d-f3892d711854.png)

Despite following all the steps, this is what I see.
![Screenshot 2021-01-04 at 10 44 17 PM](https://user-images.githubusercontent.com/1282847/103560784-62123a00-4ede-11eb-8075-d35a0d1b5acf.png)

Can you please let me know what am I doing wrong?

Thanks

**Comment by abhisheksha** [comment]
I am using Powerlevel10k

**Comment by avdv** [comment]
Hi.

colorls tries to adhere to your locale settings. It will encode output in your configured external encoding; not showing the icons if it cannot encode them.

Look at the output of `locale` and make sure to set `LC_CTYPE` to some UTF-8 locale, e.g. by `export LANG=en_US.UTF_8`.

**Comment by abhisheksha** [comment]
Thank you, so previously, my locale was giving the following output:

`locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=`

I added the following to the zshrc:
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"

restarted iTerm2
tried colorls, this is what I see as the error now
`WARN: error calling `setlocale(LC_COLLATE, "")`, check your locale settings`

But, I still don't see the icons.

locale looks like this now:

`locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8`


Came across another issue on this repo -> https://github.com/athityakumar/colorls/issues/203 

I ran `ruby -r clocale -e 'CLocale.setlocale(CLocale::LC_CTYPE, "")'`

![Screenshot 2021-01-05 at 1 59 36 AM](https://user-images.githubusercontent.com/1282847/103576774-ab23b780-4ef9-11eb-81da-ac2a000be5d5.png)

I have also installed `gem install clocale`
![Screenshot 2021-01-05 at 2 01 01 AM](https://user-images.githubusercontent.com/1282847/103576914-ddcdb000-4ef9-11eb-97df-003d6b0bef67.png)

This command was successful:
`ruby -r clocale -e 'CLocale.setlocale(CLocale::LC_COLLATE, "C")'`
![Screenshot 2021-01-05 at 2 01 55 AM](https://user-images.githubusercontent.com/1282847/103576985-fd64d880-4ef9-11eb-9c91-6f2cfc52027c.png)

but I still see the error 

Output of `Terminal` tab in iTerm2
![Screenshot 2021-01-05 at 2 04 22 AM](https://user-images.githubusercontent.com/1282847/103577183-559bda80-4efa-11eb-9587-048dfd1d24b2.png)

I tried the following command:
`ruby -r clocale -e 'CLocale.setlocale(CLocale::LC_COLLATE, "en_US.UTF-8")'

![Screenshot 2021-01-05 at 2 06 03 AM](https://user-images.githubusercontent.com/1282847/103577322-91cf3b00-4efa-11eb-996f-7efdf27eb5ef.png)

Output of `local -a`
![Screenshot 2021-01-05 at 2 07 01 AM](https://user-images.githubusercontent.com/1282847/103577385-b3c8bd80-4efa-11eb-904a-e27e175a49cc.png)


What must I do? Thank you

**Comment by avdv** [comment]
You could use the `C.UTF_8` locale that is available on your system instead. I have no idea how to troubleshoot this on darwin / macos... maybe you need to generate locale information somehow?

**Comment by abhisheksha** [comment]
I changed my locale to C.UTF_8

```
~ ❯ locale                                                                                                                             kali@kali
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=C.UTF_8
LANGUAGE=C.UTF_8
LC_CTYPE="C.UTF_8"
LC_NUMERIC="C.UTF_8"
LC_TIME="C.UTF_8"
LC_COLLATE="C.UTF_8"
LC_MONETARY="C.UTF_8"
LC_MESSAGES="C.UTF_8"
LC_PAPER="C.UTF_8"
LC_NAME="C.UTF_8"
LC_ADDRESS="C.UTF_8"
LC_TELEPHONE="C.UTF_8"
LC_MEASUREMENT="C.UTF_8"
LC_IDENTIFICATION="C.UTF_8"
LC_ALL=C.UTF_8
```


However, I still the error:
WARN: error calling `setlocale(LC_COLLATE, "")`, check your locale settings 
when executing `colorls`

**Comment by avdv** [comment]
Maybe this helps: https://blog.remibergsma.com/2012/07/10/setting-locales-correctly-on-mac-osx-terminal-application/

i.e. disable the "set locale variables automatically" in iTerm2

**Comment by abhisheksha** [comment]
Thank you for pointing me in the right direction. While that didn't have any effect, I did these commands:

```
$ sudo locale-gen "en_US.UTF-8"
Generating locales...
  en_US.UTF-8... done
Generation complete.

$ sudo dpkg-reconfigure locales
Generating locales...
  en_US.UTF-8... up-to-date
Generation complete.
```

And, after that the icons were populating :D 

![Screenshot 2021-01-05 at 3 18 30 PM](https://user-images.githubusercontent.com/1282847/103631669-4607aa80-4f69-11eb-9b23-49358d605311.png)

Btw, why is there a delay in doing colorls vs. regular ls?

**Comment by abhisheksha** [comment]
actually, let me close this issue, thank you for your support

**Comment by avdv** [comment]
@abhisheksha glad you got it to work.

> Btw, why is there a delay in doing colorls vs. regular ls?

Well, this is a Ruby project, which means it is interpreted each time you start it and this has an overhead. Try `time ruby -e 'require "colorls"'` and you see how much time it takes to load the program, before colorls even starts doing something... (on my system it's around 100ms)

Because of this, I have started a clone: https://github.com/avdv/scalals -- it does not have all the features (yet), but is fast (for a simple directory listing 6ms vs. 180ms for colorls).
