### ISSUE TITLE
doenst show dots in dotfiles names with 'colorls -A'

### ISSUE THREAD

**Issue by ivanovtd** [athityakumar/colorls#433]
When I'm running colorls -A(or colorls -a / colorls -la) filenames like .bashrc or .zshrc or other dotfiles appears without first dot in names, (screenshot given)
https://prnt.sc/wj5561

Also when i highlight file, a dot in the name appears, but only to file where i've started highlighting. 
https://prnt.sc/wj54gc

This problem doesn't appear on my mac, with the same colorls version (1.4.3)

- Type of issue :
  - [ ] Bug in existing feature

**Comment by avdv** [comment]
That seems to be a problem with your font settings. Which font are you using? 

Does this also appear to be a problem when you use `ls`?

**Comment by ivanovtd** [comment]
No, using /usr/bin/ls problem not reproduced. I'm currently using Hack Font, also tried awesome, same behavior.

![Screenshot_20210112_165201](https://user-images.githubusercontent.com/25122567/104322975-a1501480-54f6-11eb-80c9-f0fecf69b89d.png)
![Screenshot_20210112_165212](https://user-images.githubusercontent.com/25122567/104322977-a2814180-54f6-11eb-8247-944347720ed9.png)

As you can see problem steel remains after changing font. After trying several more fonts i've seen some that are showing all dots in file names, but they are quite ugly. Could you suggest fonts(also tried awesome, same behavior)?

**Comment by avdv** [comment]
It should work with any one of the Nerd Fonts => https://www.nerdfonts.com/font-downloads
