### ISSUE TITLE
Non Readable Color

### ISSUE THREAD

**Issue by SupianIDz** [athityakumar/colorls#434]
I have previously tried following the instructions https://github.com/athityakumar/colorls#custom-configurations

But unlucky, the unreadable yellow color remained unchanged. 

I used Guake with the One Light color scheme.

- Type of issue :
  - [x] Installation
![Screenshot from 2021-01-10 09-43-16](https://user-images.githubusercontent.com/37969970/104112377-17068580-5329-11eb-8320-4e380327f109.png)

**Comment by avdv** [comment]
Please show your config.

Which version of colorls are you using and how are you calling it?

**Comment by SupianIDz** [comment]
@avdv sorry for late reply.
I'm using version 1.4.3 with a color configuration like this.

~/.config/colorls/light_colors.yaml

```
# Main Colors
unrecognized_file: darkred
recognized_file:   darkgreen
dir:               navyblue

# Link
dead_link: red
link:      cyan

# special files
socket:    darkgray
blockdev:  darkgray
chardev:   darkgray

# Access Modes
write:     red
read:      sienna
exec:      navyblue
no_access: black

# Age
day_old:     darkred
hour_old:    saddlebrown
no_modifier: black

# File Size
file_large:  darkred
file_medium: saddlebrown
file_small:  black

# Random
report: black
user:   darkblue
tree:   cyan
empty:  gold
error:  red
normal: black

# Git
addition:     chartreuse
modification: darkkhaki
deletion:     darkred
untracked:    darkorange
unchanged:    darkgreen
```

**Comment by avdv** [comment]
When you are using the light colors config, you also have to use the `--light` flag, otherwise colorls will use the `dark_colorls.yaml` file.

**Comment by SupianIDz** [comment]
@avdv wo, it's worked, thanks
