### ISSUE TITLE
feature request: toggle output of link column in long format

### ISSUE THREAD

**Issue by draptik** [athityakumar/colorls#440]
### Description

We can already hide the group column with `-G`.

Can we also have a flag for hiding the "link" column (see screenshot)? This is the column between the permissions and the username column.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

![2021-01-20_17-00](https://user-images.githubusercontent.com/313058/105201603-590da380-5b41-11eb-8739-10e1e7f03f5f.png)

**Comment by avdv** [comment]
Sure, we could introduce a new command line option, say `--no-hardlinks` (so it does not interfere with GNU ls command line options). You'd like to come up with a PR?

**Comment by draptik** [comment]
sorry, I won't be able to provide a PR because my ruby skills are close to zero :-(

**Comment by t-mangoe** [comment]
As a test, I added the option `--no-hardlinks` to hide the link column.
How is this?

![スクリーンショット 2022-02-05 9 24 39](https://user-images.githubusercontent.com/22494246/152630898-724c20e7-6342-431b-b345-73f2503fb97b.png)

**Comment by draptik** [comment]
@t-mangoe looks great!

**Comment by t-mangoe** [comment]
@draptik
Thank you for your comment.
I am thinking of adding a test and sending a pull request.
It may take some time, so I hope you will be patient.
