### ISSUE TITLE
tabcomplete does not work

### ISSUE THREAD

**Issue by scila1996** [athityakumar/colorls#448]
Hi ! I use zsh with ohmyzsh + poweline10k. And was installed colorls success, but i want it colored for tab complete with option

```
source $(dirname $(gem which colorls))/tab_complete.sh
```

But seem like it does not work !

**Comment by avdv** [comment]
Hi.

You have to be more specific. What did you do, what was your expectation, what did not work?

**Comment by scila1996** [comment]
when i tab to list file. i does not work :((

![image](https://user-images.githubusercontent.com/17109300/111092832-c817df00-8569-11eb-8af5-80e733c35198.png)

**Comment by avdv** [comment]
You need to make sure that you source the `tab_complete.sh` *before* calling `compinit` in your shell initialization.

To test the completions, just run `compinit` manually and it should work in your local shell. I guess oh-my-zsh has some guidance where to put completion initialization code...
