### ISSUE TITLE
Blank line before `lc` output

### ISSUE THREAD

**Issue by soctar** [athityakumar/colorls#45]
When `lc` runs, there's a blank line before any output is printed. I know nothing about ruby - is it possible to remove this, or give an option of removing it (-q or similar)?

Really awesome work though! I'm a sucker for nice terminal enhancements.

**Comment by athityakumar** [comment]
Haha, it is indeed quite easy to remove this. But I intended to have this, to make sure the output isn't crowded with this prompt line. Are you sure that removing the newline is worth a flag? 😄

**Comment by soctar** [comment]
I figured it might be nice to give a feature without alienating the user base, if it's a feature that most people want then it doesn't need a flag. Like, default behavior should be pretty nice for everyone, I feel like the newline gives that, but some people (me) might want something different? If it's a flag, definitely #28 is more valuable to do first.

**Comment by athityakumar** [comment]
@soctar - Sure, but I'm not sure if this is worth a flag option though. Iif you'd like to have a quick  workaround, try this -

- Open the `core.rb` file in your text editor (say, `subl`) with `subl $(gem which colorls)/../colorls/core.rb`.
- Remove the first line (`print "\n"`) in the `ls_line()` method in the `core.rb` file.

But maybe if there's more request for this option, it can definitely be added as a flag option. 😄
