### ISSUE TITLE
Please add the list time format configuration

### ISSUE THREAD

**Issue by cycle2zhou** [athityakumar/colorls#471]
### Description

Please add the list time format configuration, so that users can customize the time format.
![image](https://user-images.githubusercontent.com/33155330/130178263-6717e4db-311d-4c4b-9932-8458ae91f2fa.png)

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Related to #395
