### ISSUE TITLE
Adding LibreOffice extensions

### ISSUE THREAD

**Issue by gheritarish** [athityakumar/colorls#474]
### Description

As shown in the screenshot below, the `odt` extension isn't recognized. The same can be said for `ods` or `odp` files. Since LibreOffice is default on several Linux distro, I would be for including those extensions in the file_aliases yaml.

![image](https://user-images.githubusercontent.com/21083018/132068000-4b6b9fa3-caf0-46ed-a96e-2ca239ec1f36.png)

If that's okay for you, I can implement it: I did it locally, but I think it's something that everyone can profit of.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Hi. Sounds reasonable to me :+1:

**Comment by avdv** [comment]
Done in #475
