### ISSUE TITLE
colorls in fish shell

### ISSUE THREAD

**Issue by Akash-S1999** [athityakumar/colorls#477]
does colorls work with fish shell? If yes, can you please tell me what files do I need to modify?

**Comment by avdv** [comment]
Hey @Akash-S1999 , did you get it to work? It would be nice if you could say what you did to help others coming here looking for the same problem. Thanks!

**Comment by Akash-S1999** [comment]
**Yes**, I figured it out. 
I installed cololrls as mentioned in the colorls **[README](https://github.com/athityakumar/colorls#installation)**. 
Since i am using ohmyfish, I set an alias (ls="colorls" in my omf.fish located in the directory **/home/username/.config/fish/conf.d**
And done!

Note : If you are not using ohmyfish, you can set an alias in your fish config.

Here is a screenshot of colorls in action in fish shell.
![colorls_in_fish](https://user-images.githubusercontent.com/52990376/134004538-24c10125-332c-4e4f-8857-15e20c9b721a.png)
