### ISSUE TITLE
Support -gs / --git-status flag

### ISSUE THREAD

**Issue by joeytwiddle** [athityakumar/colorls#48]
I wrote [a short shellscript](https://github.com/joeytwiddle/jsh/blob/master/code/shellscript/nicels/gitls.sh) that works like `ls -lrt` but displays the git status next to each file displayed, as shown in the `[..]` here:

![joey s xterm at 10 52 12 am on saturday 8 july 2017](https://user-images.githubusercontent.com/911799/27982076-b4af141a-63cb-11e7-92fd-07184afe90e9.png)

**You could consider adding a similar feature to `lsc`.**

The git status of each file could be indicated either using an icon, or using color (on the icon, or on the file).

(There are other versioning systems than git, so it might be good to leave room for them in future.)

**Comment by athityakumar** [comment]
@joeytwiddle - Thanks for filing this issue. Accepted. 😄 

In case someone is interested in adding this to `colorls`, please refer to this elementary approach I have in my mind : (Feel free to come up with other approaches though)

```ruby
Dir.chdir(@input) # change to given input directory
status = `git status` # get output of git status
if status.empty? || status.include?('nothing to commit, working tree clean')
    # print just [ ] in white color
else
   status = status.split("\n\n\t")
   status.delete_at(0)
   if status.first.include?('new file:')
      added_files = first.split("\n").keep_if { |y| y.include? 'new file:' }.map { |y| y.gsub('new file:', '').chomp.strip }
      status.delete_at(0)
      unadded_files = status.first.map(&:strip)
      # But what happens if added / unadded files are grouped within a folder?
   end   
```

**Comment by athityakumar** [comment]
The above approach is too naive to work well with the `--tree` flag. Rather, the [git gem](https://github.com/schacon/ruby-git) can be used.

```ruby
require 'git'
instance = Git.open '.'
instance.ls_files.keys[1..-1] # All files tracked by git
instance.status.added.keys # Added files
instance.status.untracked.keys # Untracked files
instance.status.untracked.keys # Changed files
```
