### ISSUE TITLE
Font installed - no icons

### ISSUE THREAD

**Issue by as-ninh** [athityakumar/colorls#487]
### Description

So I'm on Arch Linux + Alacritty (same issue with konsole). I'm using bash.
I believe I have the font installed correctly. Since I have icons in my NERDtree, and I have no problem viewing the icons in the .yaml files with VIM (ss attached).
Anything I should look into?

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ x] Bug in existing feature

All 3 screenshots for NERDtree, .yaml file, and colorls : https://imgur.com/a/3yFakhm

**Comment by avdv** [comment]
What is the output of locale? You should use a locale capable of displaying Unicode characters for the LC_CTYPE category.

**Comment by as-ninh** [comment]
> What is the output of locale? You should use a locale capable of displaying Unicode characters for the LC_CTYPE category.

Perfect. That was the problem. Thanks for the quick help!
