### ISSUE TITLE
What are the required fonts?

### ISSUE THREAD

**Issue by TorhamDev** [athityakumar/colorls#494]
Hello.
I have colorls installed on my system but the icons are not displayed properly
I think the problem is the font required by the program
What font should I install?

**colorls output**
![Screenshot from 2022-01-04 20-26-48](https://user-images.githubusercontent.com/87639984/148095327-fa32e71b-aa5e-4c43-a99a-534fbd4b42bc.png)

**Comment by avdv** [comment]
Hi.

You just need to install *any* nerd font and configure your terminal to use it.

**Comment by TorhamDev** [comment]
@avdv 
hi,
I tried to install nerd fonts before but the nerd font repository is too big and I could not clone it

**Comment by avdv** [comment]
You don't have to. Just go to https://www.nerdfonts.com/font-downloads and download one from there.

**Comment by TorhamDev** [comment]
Thanks, the problem was solved :)
