### ISSUE TITLE
Identifying folder names separated by spaces

### ISSUE THREAD

**Issue by kaustubhhiware** [athityakumar/colorls#5]
There is some issue related to detecting folders whose names contain spaces. 
For instance, a folder named `MEGAsync Downloads` is displayed in white, which means it is unrecognised. 
Since the listing is alphabetical, there is another folder named `Downloads` way above.

![image](https://user-images.githubusercontent.com/11318551/27752761-4db3766e-5e00-11e7-99af-a325ef8609e5.png)

**Comment by athityakumar** [comment]
@kaustubhhiware - Check if this has been fixed as per commit 1fbd3a723b716ef20797b52781f10f07eff95e9e?

**Comment by kaustubhhiware** [comment]
Fixed as per commit `405b3f0`
![image](https://user-images.githubusercontent.com/11318551/27762810-b54230ae-5e96-11e7-8c3f-f0adcd992499.png)
