### ISSUE TITLE
Rename default branch to `main`

### ISSUE THREAD

**Issue by avdv** [athityakumar/colorls#504]
### Description

Starting in 2020, many projects began renaming the default branch since the name "master" is seen as no longer appropriate.

See https://sfconservancy.org/news/2020/jun/23/gitbranchname/

We should follow suite and rename the default branch to "main".

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by athityakumar** [comment]
MSTM, renamed the master branch to main :+1:
