### ISSUE TITLE
Add API key to publish to RubyGems

### ISSUE THREAD

**Issue by avdv** [athityakumar/colorls#509]
### Description

I did just merge #505 which seems to work as expected: https://github.com/athityakumar/colorls/runs/5623825339?check_suite_focus=true -- only thing missing is the API key.

@athityakumar could you please add a repository secret called `RUBYGEMS_API_KEY` with a valid API key for publishing?

- Relevant Issues : (none)
- Relevant PRs : #505 
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by dhruvkb** [comment]
I don't mean to be rude but @athityakumar seems to be very inactive on GitHub, their last commit to GitHub was on January 16, 2022.

**Comment by athityakumar** [comment]
@avdv - Sorry, missed this thread earlier as I was travelling that week. I've created a repository secret for the RubyGems API key, can you please check it once and see if it works?

![image](https://user-images.githubusercontent.com/17109060/161385759-1f4d506d-145c-4dff-a32b-638f02f319cd.png)

**Comment by avdv** [comment]
Thank you, @athityakumar ! Publishing was successful... :rocket:
