### ISSUE TITLE
Could not get it up and running on OS X

### ISSUE THREAD

**Issue by black-perl** [athityakumar/colorls#51]
Good work !

Upon installation of Nerd fonts, colorls is not working for me. Throwing the following error:
<img width="1438" alt="screen shot 2017-07-08 at 12 41 25 pm" src="https://user-images.githubusercontent.com/5263761/27983504-3a1962ae-63db-11e7-91a3-62c04846da8e.png">

<img width="461" alt="screen shot 2017-07-08 at 12 45 21 pm" src="https://user-images.githubusercontent.com/5263761/27983507-53a08b1c-63db-11e7-9596-7b7a23adbe2b.png">

I installed colorls using gem only and nerd fonts using homebrew.
Let me know if you can reproduce it or need any further help from my side on reproducing it.

**Comment by athityakumar** [comment]
@black-perl - Thanks for filing this issue. What's your ruby version? Also, try `gem update psych`.

**Comment by black-perl** [comment]
Ruby version:
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

Fixed : 
<img width="1438" alt="screen shot 2017-07-08 at 1 45 11 pm" src="https://user-images.githubusercontent.com/5263761/27983832-b77b76a8-63e3-11e7-8110-1ae0429afcfb.png">

Thanks !
