### ISSUE TITLE
Ruby cannot close file directory when using `--git-status` (or `--gs`)

### ISSUE THREAD

**Issue by sRavioli** [athityakumar/colorls#517]
# Description

Hello, when running `$ colorls --git-status` or `$ colorls --gs` the following line gets printed before any file gets listed:

~~~sh
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/colorls-1.4.6/lib/colorls/git.rb:55: warning: cannot close fd before spawn
~~~

Compared with `$ colorls`:

![immagine](https://user-images.githubusercontent.com/76562615/164441191-8f31da2c-8828-42cb-a982-f0158c318bec.png)

## `--git-status` with `--tree`

I have created a shell alias to combine the tree view with the status of the git repo:

~~~sh
alias lsgt='colorls --sort-dirs --git-status --tree'
~~~

When running `$ lsgt` the previous message will be printed as usual, it will then be printed after every occurrence of ` dir/`:

![immagine](https://user-images.githubusercontent.com/76562615/164442201-48422ba5-cecd-42fa-925d-6f0e237f984b.png)

Compare with `$ colorls --sort-dirs --tree`:

![immagine](https://user-images.githubusercontent.com/76562615/164443756-4ff2d7e9-586c-42f8-af0c-b802596df858.png)

## `--git-status` on non git repos

The message will be printed even if the directory is not a git repo. Running `$ colorls --almost-all --gs` on the fish shell results in the following:

![immagine](https://user-images.githubusercontent.com/76562615/164442873-d16d04fe-1c29-4da6-bf41-5709290cac2f.png)

### Environment
I am using Git Bash on Windows. This does occur also on PW, CMD and fish shell (on MINGW6/MSYS)

---

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
Thanks for the report. That's a warning from Ruby caused by some deficiency of your platform.

Try to set `RUBYOPT=-W0` in your shell. This should supress all warnings.

**Comment by sRavioli** [comment]
Setting `export RUBYOPT='-W0'` in my `.bashrc` suppresses the warning in git bash, no luck on Powershell. I've tried `set RUBYOPT='-W0'` in my `$profile` but the warning is there.

**Comment by sRavioli** [comment]
Cool! Now it works. Thanks :)

**Comment by avdv** [comment]
I'll fix this properly in the next release.
