### ISSUE TITLE
Feature request: Add support to run through xargs (show absolute path)

### ISSUE THREAD

**Issue by Knud3** [athityakumar/colorls#524]
e.g. when running `find "${PWD}" -type f -print0 | xargs -0 colorls -l` it only shows file names.

`find "${PWD}" -type f -print0 | xargs -0 ls -l` in otherhand shows files with absolute path.

**Comment by ayushpoddar** [comment]
I'd like to take it up ✋🏽

**Comment by ayushpoddar** [comment]
Update: **Issue found**

`colorls` treats file arguments differently from how `ls` does.

When the argument is file path, `colorls` just displays the file name. Whereas, `ls` displays the relative file path

**Comment by ayushpoddar** [comment]
@avdv Can we close this issue, now that the related PR has been merged

**Comment by avdv** [comment]
> @avdv Can we close this issue, now that the related PR has been merged

Yes, of course. Fixed by #594
