### ISSUE TITLE
colorls only returns folders

### ISSUE THREAD

**Issue by andreadellacorte** [athityakumar/colorls#53]
I just installed colorls on mac, ruby 2.4.1 via rbenv, and seems to work ok, but it's not showing any .dot file

neither

colorls
colorls -r
colorls -f

return any of them, while ls -altr does

**Comment by athityakumar** [comment]
@ValiumKnight - Thanks for filing this issue. Use the `-a` flag please. Like,  `colorls -a -r`. If you'd like the `-a`
flag by default, have a look at the Recommended configurations mentioned in the README. 😄

**Comment by ValiumKnight** [comment]
Thank you! This seems to contradict what the README.md says:

*Just lc : Prints all directories, files and dotfiles in current directory.*

**Comment by athityakumar** [comment]
Ah, this was prior to the addition of the `-a` flag. This should be changed.

**Comment by mscottnelson** [comment]
this was an issue for me as well

**Comment by athityakumar** [comment]
@mscottnelson - As you can see from the above discussion, do try `colorls -a` if you haven't already. Also, please feel free to edit the README and send a Pull Request for future users. 😄

**Comment by mscottnelson** [comment]
Sure! Although I'm afraid I wont be making the screenshot as the other entries have...

**Comment by athityakumar** [comment]
Thanks for working on this, @mscottnelson. Fixed with PR #96 😄  👍
