### ISSUE TITLE
Is colorls available for Git Bash or Windows Command Prompt?

### ISSUE THREAD

**Issue by reddysainathn** [athityakumar/colorls#54]

**Comment by kaustubhhiware** [comment]
I think if you manage to install ruby on your windows system, and install the gem `colorls`, you should be able to use `colorls`. Can you just check this and inform if this suffices ?

**Comment by athityakumar** [comment]
@reddysainathn - Did you try the Installation steps mentioned in the README? I think the steps should be the same as long as you've Ruby. Though, I'm not sure if Windows Command Prompt has any issues with either colors, or icons.

Can you please report back on this? 😄

**Comment by reddysainathn** [comment]
I tried in Git Bash with **gem install colorls**, it did not work. Is there an alternative with npm or yarn package install?

I will try again and post the log file as I can.

**Comment by athityakumar** [comment]
@reddysainathn - Yes please, posting the log would really help. Meanwhile, can you try [this](http://foundation.zurb.com/forum/posts/8142-gem-or-foundation-command-not-found-with-git-bash-try-this) out?

**Comment by athityakumar** [comment]
@reddysainathn - Just a moment. Do you have Ruby installed? If ruby is installed, then `gem install colorls` should work properly. 😄

**Comment by reddysainathn** [comment]
I tried that, this is a duplicate of [#91](https://github.com/athityakumar/colorls/issues/91). The same log that I get. This works fine in Ubuntu.

**Comment by athityakumar** [comment]
@reddysainathn - Oh. The failing terminfo dependency has been removed, and replaced in v1.0.6. Please give `gem install colorls` another try. If the installation was successful, we can close this issue. 😄

**Comment by reddysainathn** [comment]
> Successfully installed colorls-1.0.9

Thank you.
