### ISSUE TITLE
Add COVERAGES.md

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/colorls#56]
This markdown file is intended to document the various mentions of this project. Here are some existing ones -

- https://m.youtube.com/watch?v=NESi45Q2mHg
- https://github.com/k4m4/terminals-are-sexy
- https://m.facebook.com/story.php?story_fbid=1972265916349994&id=1884586571784596
- https://openruby.com/pages/98288680-colorls-a-ruby-script-that-beautifies-the-terminals-ls
- https://openruby.com/pages/98079215-athityakumar-slash-colorls-a-ruby-script-that-beautifies-the
- http://www.omgubuntu.co.uk/2017/07/add-bling-ls-bash-command-colorls
- https://github.com/ryanoasis/nerd-fonts/wiki/Real-World-Mentions-&-Usage-(Sightings)
- https://github.com/markets/awesome-ruby
- https://github.com/uhub/awesome-shell
- https://github.com/matiassingers/awesome-readme

**Comment by mamonu** [comment]
created a pull request 
https://github.com/athityakumar/colorls/pull/126

added a mention also from Hackernews
