### ISSUE TITLE
Support -A / --almost-all

### ISSUE THREAD

**Issue by KSXGitHub** [athityakumar/colorls#57]
From `man ls`:
![image](https://user-images.githubusercontent.com/11488886/27995456-d231f268-64f8-11e7-8088-c4f8a9e93901.png)

### Expected behaviour
1. `colorls -A` list all entries except `.` and `..`
2. `colorls -a` list all entries including `.` and `..`

### Current behaviour
1. There's no `-A` nor `--almost-all`
2. Option `-a`/`--all` is doing `-A`/`--almost-all`'s jobs

**Comment by athityakumar** [comment]
Accepted. The existing `-a` should be renamed to `-A`, and support for `-a` has to be added.

**Comment by KSXGitHub** [comment]
That should be a quick fix, I guess

**Comment by adimasuhid** [comment]
@athityakumar I'll be picking this up if it's good with you.

**Comment by athityakumar** [comment]
@adimasuhid - Sure, I'm assigning this issue to you. 😄
