### ISSUE TITLE
Option for NOT human readable size - show file size in bytes

### ISSUE THREAD

**Issue by cmon1701** [athityakumar/colorls#572]
Please add an Option for NOT human readable size - show file size in bytes. I want to compare the exact file sizes to see if some files differ at least in file size. Thanks!

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [x] Feature request

**Comment by ayushpoddar** [comment]
Interested! I'd like to take this up 🚀

**Comment by ayushpoddar** [comment]
Interested! I'd like to take this up 🚀  @avdv

**Comment by avdv** [comment]
Thank you, @ayushpoddar! I have assigned you this issue.

You could either introduce a `--non-human-readable` option, or properly implement `--human-readable` / `-h` which is currently a ignored. The latter being an incompatible change, but users could always define an alias to retain the old behavior.

**Comment by ayushpoddar** [comment]
I think a --non-human-readable makes more sense because:
- it is backwards compatible
- In general, people are more interested in the human readable format. _Not many users have raised this particular issue of not having a non-human readable format_

**Comment by ayushpoddar** [comment]
@avdv Can we please close this issue?

**Comment by avdv** [comment]
Closed by https://github.com/athityakumar/colorls/pull/589
