### ISSUE TITLE
Support files in argument

### ISSUE THREAD

**Issue by KSXGitHub** [athityakumar/colorls#58]
![image](https://user-images.githubusercontent.com/11488886/27996038-5afde4a8-6503-11e7-8bf5-c954a8c13df4.png)

**P.S.** Is `colorls` supposed to works exactly like regular `ls`?

**Comment by athityakumar** [comment]
@KSXGitHub - Parsing `ls` is a discouraged approach. Hence, `colorls` in intended to work exactly like `ls` - but, currently has only some functionalities of `ls` implemented in Ruby. 😄

**Comment by KSXGitHub** [comment]
@athityakumar There're many things that do not work like in regular `ls`, for instance: `ls -l`, `ls -h`, `ls -i`, `ls -I`, etc. I'm going assume the developers didn't read [`man ls`](http://man7.org/linux/man-pages/man1/ls.1.html). Maybe I should open a seperate issue on this :smile_cat:

**Comment by athityakumar** [comment]
@KSXGitHub - There are indeed quite a lot of features of `ls` that are to be included in `colorls`. It's not that the developers didn't read `man ls`, but rather it's just how ANY software is developed. Add an initial draft, then include feature A, then feature B, etc. Right? 😄 

Meanwhile, I think @rubikonx9 already worked on this issue, but was reverted. @rubikonx9, can you please add a PR for this if you don't mind?

**Comment by rubikonx9** [comment]
Here it is: #65.

**Comment by athityakumar** [comment]
Fixed by #65. Closing this issue now.
