### ISSUE TITLE
Support for -t / --tree

### ISSUE THREAD

**Issue by luisdavim** [athityakumar/colorls#60]
It would be awesome if colorls would have a flag to print a tree output, similar to the tree command.

**Comment by athityakumar** [comment]
Accepted. 👍

**Comment by athityakumar** [comment]
Alright, assigning this to myself. 😄

**Comment by athityakumar** [comment]
Fixed with PR #82, yet to be released though. 😄

**Comment by athityakumar** [comment]
@luisdavim - Released with v0.1.6. Try `gem update colorls` and then start using `colorls -t`. If any more enhancements are required in the `-t` / `--tree` flag, feel free to reopen the issue. 👍
