### ISSUE TITLE
Can't install colorls

### ISSUE THREAD

**Issue by cajuuh** [athityakumar/colorls#61]
whe i type: ```sudo gem install colorls```

i get:
```
Building native extensions.  This could take a while...
ERROR:  Error installing colorls:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ruby-terminfo-0.1.1
/usr/bin/ruby2.3 -r ./siteconf20170710-21629-gq9k0b.rb extconf.rb
checking for setupterm() in -lncurses... no
checking for setupterm() in -lcurses... no
checking for rb_io_t in ruby.h,rubyio.h... yes
checking for rb_io_t.fd in ruby.h,rubyio.h... yes
checking for OpenFile.fd in ruby.h,rubyio.h... no
creating extconf.h
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ruby-terminfo-0.1.1/mkmf.log

current directory: /var/lib/gems/2.3.0/gems/ruby-terminfo-0.1.1
make "DESTDIR=" clean

current directory: /var/lib/gems/2.3.0/gems/ruby-terminfo-0.1.1
make "DESTDIR="
compiling terminfo.c
In file included from terminfo.c:33:0:
/usr/include/ruby-2.3.0/ruby/backward/rubyio.h:2:2: warning: #warning use "ruby/io.h" instead of "rubyio.h" [-Wcpp]
 #warning use "ruby/io.h" instead of "rubyio.h"
  ^~~~~~~
terminfo.c:36:20: fatal error: curses.h: Arquivo ou diretório não encontrado
 #include <curses.h>
                    ^
compilation terminated.
Makefile:246: recipe for target 'terminfo.o' failed
make: *** [terminfo.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ruby-terminfo-0.1.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ruby-terminfo-0.1.1/gem_make.out
```
ruby version is 2.3.1, i already tried to rename the folders.

**Comment by athityakumar** [comment]
Hey @cajuuh! Thanks for filing this issue. Please try the below approaches -

1. 
```sh
sudo gem uninstall colorls
gem install colorls
```
2. 
```sh
sudo gem uninstall colorls
gem install rubygems-update
update_rubygems
gem update --system
gem install colorls
```

**Comment by cajuuh** [comment]
well firstly thank you @athityakumar for the fatest answer i ever seen on github..

apparently i don't have permission to use ```gem``` outside ```sudo```
```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.
```
i tried the steps you mentioned under ```sudo``` but got the same error:
```
Building native extensions.  This could take a while...
ERROR:  Error installing colorls:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ruby-terminfo-0.1.1
/usr/bin/ruby2.3 -r ./siteconf20170710-31319-1m7fe1r.rb extconf.rb
checking for setupterm() in -lncurses... no
checking for setupterm() in -lcurses... no
checking for rb_io_t in ruby.h,rubyio.h... yes
checking for rb_io_t.fd in ruby.h,rubyio.h... yes
checking for OpenFile.fd in ruby.h,rubyio.h... no
creating extconf.h
creating Makefile

current directory: /var/lib/gems/2.3.0/gems/ruby-terminfo-0.1.1
make "DESTDIR=" clean

current directory: /var/lib/gems/2.3.0/gems/ruby-terminfo-0.1.1
make "DESTDIR="
compiling terminfo.c
In file included from terminfo.c:33:0:
/usr/include/ruby-2.3.0/ruby/backward/rubyio.h:2:2: warning: #warning use "ruby/io.h" instead of "rubyio.h" [-Wcpp]
 #warning use "ruby/io.h" instead of "rubyio.h"
  ^~~~~~~
terminfo.c:36:20: fatal error: curses.h: Arquivo ou diretório não encontrado
 #include <curses.h>
                    ^
compilation terminated.
Makefile:246: recipe for target 'terminfo.o' failed
make: *** [terminfo.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ruby-terminfo-0.1.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ruby-terminfo-0.1.1/gem_make.out
```

**Comment by athityakumar** [comment]
@cajuuh - I'm not sure what exactly the issue is, but I think this is related to having Ruby with access levels and without any version manager like RVM, rbenv, etc. Do you have access to uninstall Ruby and install rvm? If yes, please do it and then `gem install colorls`. 😄 

Else, give a try to the steps mentioned in the `CONTRIBUTING.md` file.

**Comment by hallaksec** [comment]
I have the same error and none of the fixes worked for me.

**Comment by cajuuh** [comment]
@athityakumar - Sorry man, same error, even with the all RVM access :cry:

**Comment by athityakumar** [comment]
@hallaksec @cajuuh - Ah, just saw the `curses` mentioned in the log. Try `sudo apt-get install libncurses5-dev` and then `gem install colorls`.

**Comment by cajuuh** [comment]
@athityakumar you sir is a lord and a gentleman. :man_in_tuxedo:

**Comment by anthonyrichir** [comment]
Just for the record, I've juste experienced the same issue and installing libncurses5-dev solved the problem for me as well.

**Comment by Kuzey27** [comment]
I had a problem like this. 
But the main error was:
```
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
```
Solution for this problem is also [here](https://stackoverflow.com/questions/20559255/error-while-installing-json-gem-mkmf-rb-cant-find-header-files-for-ruby) in stackoverflow.
```
sudo apt-get install ruby`ruby -e 'puts RUBY_VERSION[/\d+\.\d+/]'`-dev
```

**Comment by synthead** [comment]
For Alpine Linux, install the `ncurses-dev` package :+1:

**Comment by shashlad7** [comment]
If anybody has still having issue, do,

`sudo apt install ruby-dev gcc make` (https://github.com/athityakumar/colorls/issues/184#issuecomment-457226781)

after this, try installing `sudo apt install colorls`

It should work.

For more info : https://github.com/athityakumar/colorls/issues/184

**Comment by zenideas** [comment]
I am on Ventura upgraded from Monterey. On new MBP M1 Pro, 10c CPU/16c GPU

When I tried to install sudo gem install colorls. 
`Fetching colorls-1.4.6.gem
Fetching rainbow-3.1.1.gem
Fetching manpages-0.6.1.gem
Fetching filesize-0.2.0.gem
Fetching clocale-0.0.4.gem
Fetching public_suffix-5.0.4.gem
Fetching addressable-2.8.6.gem
Fetching unicode-display_width-2.5.0.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.
	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:708:in `verify_gem_home'
	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:898:in `pre_install_checks'
	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:303:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/resolver/specification.rb:105:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:195:in `block in install'
	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:183:in `each'
	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:183:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:215:in `install_gem'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:231:in `block in install_gems'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:224:in `each'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:224:in `install_gems'
	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:170:in `execute'
	/Library/Ruby/Site/2.6.0/rubygems/command.rb:328:in `invoke_with_build_args'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:253:in `invoke_command'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:193:in `process_args'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:151:in `run'
	/Library/Ruby/Site/2.6.0/rubygems/gem_runner.rb:56:in `run'
	/usr/bin/gem:21:in `<main>'`

Then following AdithyaKumar:

`sudo update_rubygems       
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted @ rb_sysopen - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/gem
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1387:in `initialize'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1387:in `open'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1387:in `block in copy_file'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1386:in `open'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1386:in `copy_file'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:492:in `copy_file'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:860:in `block in install'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1558:in `block in fu_each_src_dest'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1574:in `fu_each_src_dest0'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1556:in `fu_each_src_dest'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:856:in `install'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.22/lib/rubygems/commands/setup_command.rb:268:in `block (2 levels) in install_executables'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.22/lib/rubygems/commands/setup_command.rb:252:in `chdir'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.22/lib/rubygems/commands/setup_command.rb:252:in `block in install_executables'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.22/lib/rubygems/commands/setup_command.rb:249:in `each'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.22/lib/rubygems/commands/setup_command.rb:249:in `install_executables'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.22/lib/rubygems/commands/setup_command.rb:166:in `execute'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.22/lib/rubygems/command.rb:328:in `invoke_with_build_args'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.22/lib/rubygems/command_manager.rb:253:in `invoke_command'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.22/lib/rubygems/command_manager.rb:193:in `process_args'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.22/lib/rubygems/command_manager.rb:151:in `run'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.22/lib/rubygems/gem_runner.rb:56:in `run'
	setup.rb:36:in `<main>'`

> Hey @cajuuh! Thanks for filing this issue. Please try the below approaches -
> 
> 
> ```shell
> sudo gem uninstall colorls
> gem install colorls
> ```
> 
> 
> ```shell
> sudo gem uninstall colorls
> gem install rubygems-update
> update_rubygems
> gem update --system
> gem install colorls
> ```

**Comment by Jay-Karia** [comment]
This is what I did on **Fedora 41**:
```
sudo dnf install ruby-devel
```
```
sudo dnf install ncurses-devel
```
```
gem install colorls
```
