### ISSUE TITLE
Icons for specific files (match with filename, not extension)

### ISSUE THREAD

**Issue by Jab2870** [athityakumar/colorls#62]
It would be great if, I was able to use the grunt icon for files named `Gruntfile.js` (\ue74c).

I tried adding: `Gruntfile.js   grunt` to the file_aliases.yaml ad adding `grunt   "\ue74c"` to the files.yaml but it didn't work.

**Comment by athityakumar** [comment]
@Jab2870 - Currently, filenames' extension is decided by the part after the last dot. So, a `Gruntfile.js` gets recognized as a `.js` file. 

Recognizing certain files by exact name isn't supported yet, but should be a goo addition.

**Comment by athityakumar** [comment]
If anyone would like to take this up, the private method `ColorLS::Core#options` has to be modified with probably just 2-3 lines. 😄
