### ISSUE TITLE
Getting lots of warnings when attempting to use?

### ISSUE THREAD

**Issue by tomchapin** [athityakumar/colorls#69]
When I install colorls on my mac (with Ruby 2.4.1p111) and use it, it is working, but I get a bunch of warnings?

```
/usr/local/Cellar/rbenv/1.1.0/versions/2.4.1/lib/ruby/gems/2.4.0/gems/facets-3.1.0/lib/core/facets/filetest/separator_pattern.rb:4: warning: already initialized constant FileTest::SEPARATOR_PATTERN
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/facets-3.1.0/lib/core/facets/filetest/separator_pattern.rb:4: warning: previous definition of SEPARATOR_PATTERN was here
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/facets-3.1.0/lib/core/facets/kernel/ergo.rb:29: warning: already initialized constant NilClass::FUNCTOR
/usr/local/Cellar/rbenv/1.1.0/versions/2.4.1/lib/ruby/gems/2.4.0/gems/facets-3.1.0/lib/core/facets/kernel/ergo.rb:29: warning: previous definition of FUNCTOR was here
/usr/local/opt/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/facets-3.1.0/lib/core/facets/string/bracket.rb:3: warning: already initialized constant String::BRA2KET
/usr/local/Cellar/rbenv/1.1.0/versions/2.4.1/lib/ruby/gems/2.4.0/gems/facets-3.1.0/lib/core/facets/string/bracket.rb:3: warning: previous definition of BRA2KET was here
```

**Comment by athityakumar** [comment]
@tomchapin - Thanks for filing this issue 😄 . Try adding this to your shell configuration file (`~/.bashrc`, `~/.zshrc` or `~/.fishrc`) -

```sh
export RUBYOPT="-W0"
```

**Comment by tomchapin** [comment]
@athityakumar Thank you for that tip! I'm not comfortable with globally disabling Ruby warnings (since I'm a Ruby developer and need to know if my code is throwing warnings), but I think I found a happy compromise. I just added that environment variable directly to my colorls "lc" alias, like so:

```
alias lc='RUBYOPT="-W0" colorls -l -a'
```

**Comment by athityakumar** [comment]
@tomchapin - These warnings are related to the gems used by `colorls` and not directly due to `colorls`. This may infact be the only happy workaround for now, unless the gems are updated too. (Or of course, you can also downgrade your Ruby version, but meh) 😄
