### ISSUE TITLE
Weighed colours for '-l' flag

### ISSUE THREAD

**Issue by pjcj** [athityakumar/colorls#76]
I used to use k (https://github.com/supercrabtree/k) but it has too many differences to ls.  One really nice feature it has, though, is to weight the colours according to file size and age - large file sizes are more red, smaller are more green, and newer files are lighter, older are darker.

I'd love to see such a feature in colorls.  This seems feasible now the -l option has been implemented.

**Comment by athityakumar** [comment]
@pjcj - Thanks for filing this issue. The `-l` flag already colors the date / time as per last usage. Similar criteria can be used to be colorize file sizes as well. Is this intended to work only with `-l` flag?

**Comment by pjcj** [comment]
Ah, I hadn't realised the ageing colours were already implemented.  (I have ruby 1.9.1 from Ubuntu 14.04, and colorls seems not to work with it, but that's another story.)  The sizes only really makes sense with the -l flag, because that's where the size is reported, but the ageing could also work on standard output, if it is the name of the file which is being coloured.  This is the way in which k works, and it seems quite sensible to me.

**Comment by athityakumar** [comment]
Updated the issue name. Weighed colors are already implemented for the date column of `colorls`. This has to be extended for file sizes as well.

**Comment by GladOSkar** [comment]
What breakponts would be reasonable here? 1k, 1M, 1G?

**Comment by pjcj** [comment]
This is what k is doing, which seems to work well enough: https://github.com/supercrabtree/k/blob/master/k.sh#L170

But I wonder whether a sliding scale would work?  More analogue, less digital?
