### ISSUE TITLE
Rename -sd flag to fit GNU's --group-directories-first

### ISSUE THREAD

**Issue by elFua** [athityakumar/colorls#79]
`colors --group-directories-first` does not work as the GNU version of `ls`, i.e. folders are not shown first.

**Comment by athityakumar** [comment]
Hey @elFua, thanks for filing this issue. Please try `colorls -sd`. :smile:

**Comment by elFua** [comment]
Thanks! `-sd` works, but it would be good to have it work the same way as GNU `ls` so that in case people decide to alias `colorls` to `ls` then all pre-existing flags will just work as is, rather than having to use rewrite the aliases specifically for `colorls`.

**Comment by rohitner** [comment]
Along with aliasing colorls to ls, you may add additional line to alias colorls -sd to ls --group-directories-first in the .bashrc file

**Comment by athityakumar** [comment]
@rohitner - Yes, but won't it be better if `colorls` by default supports `--group-directories-first` along with `--sort-directories` / `-sd`? It'd be easier for users if colorls supports GNU flags out of the box. Literally just a single line change in the `flags.rb` file. 😄
