### ISSUE TITLE
Check for order of data in YAML files

### ISSUE THREAD

**Issue by athityakumar** [athityakumar/colorls#8]
Both `aliases.yaml` and `formats.yaml` have a certain order, in which data should be inserted. Both YAML files are key-value hashes, with - 

- `aliases.yaml` : The values are sorted alphabetically. For each set of keys mapping to a value, those set of keys are also sorted alphabetically.
- `formats.yaml` : The keys are sorted alphabetically.

It'd be good to have a (Ruby?) script that automatically checks for this order, and use with Travis CI to decide when PRs are submitted.

**Comment by adimasuhid** [comment]
Hi @athityakumar Just to confirm, there has been renames to the following files from `master`:
`aliases.yaml` -> `file_aliases.yaml`
`formats.yaml` -> `files.yaml`

**Comment by athityakumar** [comment]
Sorry, forgot to update the issue details.

`aliases.yaml` -> `folder_aliases.yaml` + `file_aliases.yaml`
`formats.yaml` -> `folders.yaml` + `files.yaml`

Thanks for reminding, @adimasuhid 😄
