### ISSUE TITLE
Support for man page

### ISSUE THREAD

**Issue by elFua** [athityakumar/colorls#80]
Common flags like `-h` and `--help` are not supported.

Apart from that, no man page is defined:

```bash
$ man colorls
No manual entry for colorls
```

**Comment by athityakumar** [comment]
Thanks for filing this issue, @elFua. But, this is possibly a duplicate of issue #28. Man pages is a good enhancement though. 👍

**Comment by athityakumar** [comment]
In case anyone would like to take up this issue, [this](https://www.cyberciti.biz/faq/linux-unix-creating-a-manpage/) could be a possible guide on how to (easily) create a man page.

**Comment by athityakumar** [comment]
Support added by PR #158
