### ISSUE TITLE
Support configuration files inside home directory

### ISSUE THREAD

**Issue by Jab2870** [athityakumar/colorls#86]
I really like this plugin but it would be better if I could have configuration files somewhere in my home directory (probably something like `~/.config/colorls/`) so that any custom icons I add won't be overwritten each time there is an update. I could see this replicating the YAML folder so that any of the 4 files in the repo could be extended in the home config directory.

**Comment by athityakumar** [comment]
@Jab2870 - Thanks for the suggestion, accepted.

**Comment by melMass** [comment]
Is this implemented already ?

**Comment by athityakumar** [comment]
@melMass - Nope, this is yet to be implemented.

**Comment by lewazo** [comment]
I'll take this one.
