### ISSUE TITLE
Misc readme fixes

### ISSUE THREAD

**Issue by ryanoasis** [athityakumar/colorls#87]
Misc readme fixes: typos and Nerd Font reference improvements

Suggested changes: https://github.com/athityakumar/colorls/compare/master...ryanoasis:patch-1

Per your guidelines creating an issue first before submitting a PR :smile:

**Comment by athityakumar** [comment]
@ryanoasis - Looks good, please feel free to open a PR. 😄

**Comment by athityakumar** [comment]
@ryanoasis - When you're creating the PR for this issue, can you also include the changes as discussed in issue #33 (git icon in `files.yaml`)? 😄

**Comment by ryanoasis** [comment]
Sure I can do that, I just thought someone else already planned to.

the same icon that is being used for .gitignore I believe was the ultimate consensus?

**Comment by athityakumar** [comment]
@ryanoasis - Thanks. And yes, the same icon as .gitignore. 😄

**Comment by ryanoasis** [comment]
Sure I have updated the icon as well: https://github.com/athityakumar/colorls/compare/master...ryanoasis:patch-1?expand=1

I didn't see anything on the contributing on number of commit messages or to squash so I just added the commit to the same branch. Let me know if you want me to change this.

**Comment by athityakumar** [comment]
No need to squash, this looks good. :smile:
