### ISSUE TITLE
Installation Fails on Windows

### ISSUE THREAD

**Issue by Baneeishaque** [athityakumar/colorls#91]
prism@PRISM-PC D:\Programs\Codes\CMD_Ruby\colorls
    $ gem install colorls
	Temporarily enhancing PATH for MSYS/MINGW...
	Building native extensions.  This could take a while...
	ERROR:  Error installing colorls:
	ERROR: Failed to build gem native extension.
	current directory: D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-terminfo-0.1.1
	D:/Programs/Ruby24-x64/bin/ruby.exe -r ./siteconf20170727-6524-r8myxr.rb extconf.rb
	checking for setupterm() in -lncurses... no
	checking for setupterm() in -lcurses... no
	checking for rb_io_t in ruby.h,rubyio.h... yes
	checking for rb_io_t.fd in ruby.h,rubyio.h... yes
	checking for OpenFile.fd in ruby.h,rubyio.h... no
	creating extconf.h
	creating Makefile

	current directory: D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-terminfo-0.1.1
	make "DESTDIR=" clean

	current directory: D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-terminfo-0.1.1
	make "DESTDIR="
	generating terminfo-x64-mingw32.def
	compiling terminfo.c
	In file included from terminfo.c:33:0:
	D:/Programs/Ruby24-x64/include/ruby-2.4.0/ruby/backward/rubyio.h:2:2: warning: #warning use "ruby/io.h" instead of "rubyio.h" [-Wcpp]
	 #warning use "ruby/io.h" instead of "rubyio.h"
	  ^~~~~~~
	terminfo.c:36:10: fatal error: curses.h: No such file or directory
	 #include <curses.h>
			  ^~~~~~~~~~
	compilation terminated.
	make: *** [Makefile:249: terminfo.o] Error 1

	make failed, exit code 2

	Gem files will remain installed in D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-terminfo-0.1.1 for inspection.
	Results logged to D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/ruby-terminfo-0.1.1/gem_make.out

	prism@PRISM-PC D:\Programs\Codes\CMD_Ruby\colorls
	$ bundle install
	Fetching gem metadata from https://rubygems.org/...........
	Fetching version metadata from https://rubygems.org/..
	Resolving dependencies...
	Using rake 12.0.0
	Using ast 2.3.0
	Using bundler 1.15.3
	Using colorize 0.8.1
	Using facets 3.1.0
	Using filesize 0.1.1
	Fetching ruby-terminfo 0.1.1
	Installing ruby-terminfo 0.1.1 with native extensions
	Using diff-lcs 1.3
	Using diffy 3.2.0
	Using parallel 1.12.0
	Using powerpack 0.1.1
	Using rspec-support 3.6.0
	Using ruby-progressbar 1.8.1
	Using unicode-display_width 1.3.0
	Using rainbow 2.2.2
	Using parser 2.4.0.0
	Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

	current directory:
	D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-terminfo-0.1.1
	D:/Programs/Ruby24-x64/bin/ruby.exe -r ./siteconf20170727-3460-1q8cqfz.rb
	extconf.rb
	checking for setupterm() in -lncurses... no
	checking for setupterm() in -lcurses... no
	checking for rb_io_t in ruby.h,rubyio.h... yes
	checking for rb_io_t.fd in ruby.h,rubyio.h... yes
	checking for OpenFile.fd in ruby.h,rubyio.h... no
	creating extconf.h
	creating Makefile

	current directory:
	D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-terminfo-0.1.1
	make "DESTDIR=" clean

	current directory:
	D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-terminfo-0.1.1
	make "DESTDIR="
	generating terminfo-x64-mingw32.def
	compiling terminfo.c
	In file included from terminfo.c:33:0:
	D:/Programs/Ruby24-x64/include/ruby-2.4.0/ruby/backward/rubyio.h:2:2: warning:
	#warning use "ruby/io.h" instead of "rubyio.h" [-Wcpp]
	 #warning use "ruby/io.h" instead of "rubyio.h"
	  ^~~~~~~
	terminfo.c:36:10: fatal error: curses.h: No such file or directory
	 #include <curses.h>
			  ^~~~~~~~~~
	compilation terminated.
	make: *** [Makefile:249: terminfo.o] Error 1

	make failed, exit code 2

	Gem files will remain installed in
	D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-terminfo-0.1.1 for
	inspection.
	Results logged to
	D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/ruby-terminfo-0.1.1/gem_make.out

	An error occurred while installing ruby-terminfo (0.1.1), and Bundler
	cannot continue.
	Make sure that `gem install ruby-terminfo -v '0.1.1'` succeeds before
	bundling.

	In Gemfile:
	  colorls was resolved to 0.1.7, which depends on
		ruby-terminfo

	prism@PRISM-PC D:\Programs\Codes\CMD_Ruby\colorls
	$ ruby -v
	ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]

	prism@PRISM-PC D:\Programs\Codes\CMD_Ruby\colorls

**Comment by athityakumar** [comment]
Hey @Baneeishaque, thanks for filing this issue. Can you try installing the curses library? (`sudo apt-get install libncurses5-dev libncursesw5-dev` works for Linux systems, but I'm sure you will find it's WIndows equivalent) 😄

**Comment by Baneeishaque** [comment]
$ gem install colorls
    Temporarily enhancing PATH for MSYS/MINGW...
    Building native extensions.  This could take a while...

MSYS2 is used for building native extensions, MSYS2 uses `pacman` as package manager (Arch linux and some other distros also using `pacman` as package manager. I am a windows guy and not much aware about pacman. can you suggest how to use these commands (`sudo apt-get install libncurses5-dev libncursesw5-dev`) on pacman, i already tried `pacman -Syuu ncurses` ( i don't what exactly it is...), and installed ncurses on MSYS2 successfully, but, error is still there...

**Comment by Baneeishaque** [comment]
I got these two links [ncurses 6.0+20170527-1](https://www.archlinux.org/packages/core/x86_64/ncurses/), [[Solved] Where is ncurses-dev? (missing .h file)](https://bbs.archlinux.org/viewtopic.php?id=117029); they says there is no `-dev package`. only `ncurses` exist, but i already installed ncurses. This is the steps takes to install `ncurses` on MSYS2 : 


	prism@prism-PC MINGW64 ~
	$ pacman -Syuu ncurses
	:: Synchronizing package databases...
	 mingw32 is up to date
	 mingw64 is up to date
	 msys is up to date
	warning: ncurses-6.0.20170708-2 is up to date -- reinstalling
	:: Starting core system upgrade...
	 there is nothing to do
	:: Starting full system upgrade...
	resolving dependencies...
	looking for conflicting packages...

	Packages (1) ncurses-6.0.20170708-2

	Total Installed Size:  9.02 MiB
	Net Upgrade Size:      0.00 MiB

	:: Proceed with installation? [Y/n] y
	(1/1) checking keys in keyring                     [#####################] 100%
	(1/1) checking package integrity                   [#####################] 100%
	(1/1) loading package files                        [#####################] 100%
	(1/1) checking for file conflicts                  [#####################] 100%
	(1/1) checking available disk space                [#####################] 100%
	:: Processing package changes...
	(1/1) reinstalling ncurses                         [#####################] 100%

	prism@prism-PC MINGW64 ~
	$

The installation is success, but the above error appears on installation of colorls.

**Comment by athityakumar** [comment]
@Baneeishaque - The terminfo dependency has been removed, and replaced in v1.0.6. Please give `gem install colorls` another try. If the installation was successful, we can close this issue. 😄

**Comment by Baneeishaque** [comment]
Now, the installation is success, but `colorls` command give me another error.

```
Srf@SRF-PC C:\Users\Srf
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]

Srf@SRF-PC C:\Users\Srf
$ gem install colorls
Fetching: filesize-0.1.1.gem (100%)
Successfully installed filesize-0.1.1
Fetching: rainbow-2.2.2.gem (100%)
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
Successfully installed rainbow-2.2.2
Fetching: colorls-1.0.9.gem (100%)

  *******************************************************************
    Changes introduced in colorls

    Sort by dirs  : -sd flag has been renamed to --sd
    Sort by files : -sf flag has been renamed to --sf
    Git status    : -gs flag has been renamed to --gs

    Clubbed flags : `colorls -ald` works
    Help menu     : `colorls -h` provides all possible flag options

    Tab completion enabled for flags
  *******************************************************************
Successfully installed colorls-1.0.9
Parsing documentation for filesize-0.1.1
Installing ri documentation for filesize-0.1.1
Parsing documentation for rainbow-2.2.2
Installing ri documentation for rainbow-2.2.2
Parsing documentation for colorls-1.0.9
Installing ri documentation for colorls-1.0.9
Done installing documentation for filesize, rainbow, colorls after 5 seconds
3 gems installed

Srf@SRF-PC C:\Users\Srf
$ color
ColorPrompt.cmd  color            colorcpl.exe     colorls.bat
Srf@SRF-PC C:\Users\Srf
$ colorls.bat
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/colorls-1.0.9/lib/colorls/core.rb:16:in ``': No such file or directory - tput cols (Errno::ENOENT)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/colorls-1.0.9/lib/colorls/core.rb:16:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/colorls-1.0.9/lib/colorls/flags.rb:39:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/colorls-1.0.9/lib/colorls/flags.rb:39:in `process'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/colorls-1.0.9/exe/colorls:4:in `<top (required)>'
        from C:/Ruby24-x64/bin/colorls:22:in `load'
        from C:/Ruby24-x64/bin/colorls:22:in `<main>'
```

**Comment by Baneeishaque** [comment]
Issue resolved...
